packages:
  - apps/*

catalog:
  "@hugeicons/core-free-icons": ^4.1.2
  "@hugeicons/react": ^1.1.6
  "@rdkit/rdkit": 2025.3.4-1.0.0
  "@tauri-apps/api": ^2.9.0
  "@tauri-apps/cli": ^2.8.4
  "@tauri-apps/plugin-dialog": ^2.4.0
  "@tauri-apps/plugin-opener": ^2.5.0
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@vitejs/plugin-react": ^4.6.0
  lefthook: ^2.1.6
  molstar: 5.7.0
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ~5.8.3
  vite: ^7.0.4
  zustand: ^5.0.7

catalogMode: prefer
