#!/usr/bin/env python3
"""Generate native AM1, PM3, and PM6_SP parameter tables from pinned CSVs."""

from __future__ import annotations

import argparse
import csv
import hashlib
import shutil
import subprocess
from pathlib import Path

AM1_SHA256 = "9bd640e9f51ec97aa88487a106f0889fa8d73778ba96b088e711c8617562008a"
PM3_SHA256 = "4f3cc3339ee86627690fac8e2ce8c45a4cf1468e2bf786ad086d76a6c66549ca"
PM6_SHA256 = "c8f9c7e4c5b8d056effd3db1cd2b7bef06726d740678ed5055da00cc805147ff"

AM1_DOMAIN = (1, 6, 7, 8, 9, 14, 15, 16, 17, 35, 53)
PM3_DOMAIN = (1, 3, 4, 6, 7, 8, 9, 12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35, 48, 49, 50, 51, 52, 53)
PM6_SP_DOMAIN = (1, 6, 7, 8, 9, 15, 16, 17, 35, 53)
VALENCE = {
    1: 1, 3: 1, 4: 2, 5: 3, 6: 4, 7: 5, 8: 6, 9: 7,
    11: 1, 12: 2, 13: 3, 14: 4, 15: 5, 16: 6, 17: 7,
    19: 1, 20: 2, 21: 3, 22: 4, 23: 5, 24: 6, 25: 7,
    26: 8, 27: 9, 28: 10, 29: 11, 30: 12, 31: 3, 32: 4,
    33: 5, 34: 6, 35: 7, 37: 1, 38: 2, 48: 12, 49: 3,
    50: 4, 51: 5, 52: 6, 53: 7,
}


def checked(path: Path, expected: str) -> None:
    observed = hashlib.sha256(path.read_bytes()).hexdigest()
    if observed != expected:
        raise SystemExit(f"{path}: SHA-256 {observed} != pinned {expected}")


def value(row: dict[str, str], key: str) -> float:
    raw = row.get(key, "").strip()
    try:
        return float(raw) if raw else 0.0
    except ValueError:
        return 0.0


def rows(path: Path) -> dict[int, dict[str, str]]:
    with path.open(newline="") as handle:
        parsed = csv.DictReader(handle, skipinitialspace=True)
        result = {}
        for raw in parsed:
            row = {key.strip(): (entry.strip() if entry else "") for key, entry in raw.items() if key}
            result[int(row["N"])] = row
        return result


def number(number_value: float) -> str:
    if number_value == 0.0:
        return "0.0"
    return repr(number_value)


def table(name: str, domain: tuple[int, ...], source: dict[int, dict[str, str]]) -> str:
    lines = [f"const {name}: [SemiempiricalElementParameters; {len(domain)}] = ["]
    for atomic_number in domain:
        row = source[atomic_number]
        if abs(value(row, "U_ss")) < 1.0e-12:
            raise SystemExit(f"{name}: element {atomic_number} has no parameters")
        orbital = [value(row, key) for key in ("U_ss", "U_pp", "zeta_s", "zeta_p", "beta_s", "beta_p")]
        repulsion = [value(row, key) for key in ("g_ss", "g_sp", "g_pp", "g_p2", "h_sp", "alpha")]
        gaussian = [
            [value(row, f"Gaussian{index}_{field}") for field in ("K", "L", "M")]
            for index in range(1, 5)
        ]
        lines.extend([
            "    element(",
            f"        {atomic_number},",
            f"        \"{row['sym']}\",",
            f"        {VALENCE[atomic_number]},",
            f"        [{', '.join(map(number, orbital))}],",
            f"        [{', '.join(map(number, repulsion))}],",
            "        [",
        ])
        lines.extend(f"            [{', '.join(map(number, record))}]," for record in gaussian)
        lines.extend(["        ],", "    ),"])
    lines.append("];")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("am1_csv", type=Path)
    parser.add_argument("pm3_csv", type=Path)
    parser.add_argument("pm6_csv", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--archive-dir", type=Path)
    args = parser.parse_args()
    checked(args.am1_csv, AM1_SHA256)
    checked(args.pm3_csv, PM3_SHA256)
    checked(args.pm6_csv, PM6_SHA256)
    output = "\n\n".join([
        "// @generated by compute/semiempirical/generate-sp-method-parameters.py",
        "#[allow(clippy::approx_constant)]\n" + table("AM1", AM1_DOMAIN, rows(args.am1_csv)),
        table("PM3", PM3_DOMAIN, rows(args.pm3_csv)),
        table("PM6_SP", PM6_SP_DOMAIN, rows(args.pm6_csv)),
    ]) + "\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output)
    subprocess.run(["rustfmt", "--edition", "2021", str(args.output)], check=True)
    if args.archive_dir:
        args.archive_dir.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(args.am1_csv, args.archive_dir / "parameters_AM1_MOPAC.csv")
        shutil.copyfile(args.pm3_csv, args.archive_dir / "parameters_PM3_MOPAC.csv")
    print(f"wrote {len(AM1_DOMAIN) + len(PM3_DOMAIN) + len(PM6_SP_DOMAIN)} parameter records")


if __name__ == "__main__":
    main()
