#!/usr/bin/env python3
"""Generate the native PM6 PWCCT pair table from the pinned MOPAC CSV."""

import argparse
import csv
import hashlib
from pathlib import Path

PINNED_SHA256 = "2fafe0ddec1d6aaec230d63bcd5959f727550418bcddd3b75d19f051661b6845"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    raw = args.source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != PINNED_SHA256:
        raise ValueError(f"source SHA-256 {digest} does not match pinned {PINNED_SHA256}")
    pairs: dict[tuple[int, int], tuple[float, float]] = {}
    for row in csv.reader(raw.decode().splitlines()):
        left, right = int(row[0]), int(row[1])
        alpha, chi = float(row[2]), float(row[3])
        if alpha != 0.0 and chi != 0.0:
            pairs[tuple(sorted((left, right)))] = (chi, alpha)
    lines = [
        "// @generated by compute/semiempirical/generate-pm6-pwcct.py; do not edit.",
        f"// Source SHA-256: {digest}",
        f"pub(super) const PM6_PWCCT: [(u8, u8, f64, f64); {len(pairs)}] = [",
    ]
    for (left, right), (chi, alpha) in sorted(pairs.items()):
        lines.append(f"    ({left}, {right}, {chi!r}, {alpha!r}),")
    lines.append("];\n")
    args.output.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
