// @generated by compute/semiempirical/generate-pm6-two-center.py; do not edit.
// Source: PYSEQM two_elec_two_center_int_local_frame_d_orbitals.py
// SHA-256: aca9f065544fb9aacddf15ace0c0cb03d887481b9fa45f71835b49c95b3b17af

#[derive(Clone, Copy, Debug)]
pub(super) struct Pm6YyLocalInput {
    pub r0: f64,
    pub da0: f64,
    pub db0: f64,
    pub qa0: f64,
    pub qb0: f64,
    pub dpa0: f64,
    pub dpb0: f64,
    pub dsa0: f64,
    pub dsb0: f64,
    pub dda0: f64,
    pub ddb0: f64,
    pub rho0a: f64,
    pub rho0b: f64,
    pub rho1a: f64,
    pub rho1b: f64,
    pub rho2a: f64,
    pub rho2b: f64,
    pub rho3a: f64,
    pub rho3b: f64,
    pub rho4a: f64,
    pub rho4b: f64,
    pub rho5a: f64,
    pub rho5b: f64,
    pub rho6a: f64,
    pub rho6b: f64,
}

#[allow(non_snake_case, unused_variables, unused_parens)]
pub(super) fn pm6_yy_local(input: Pm6YyLocalInput) -> [f64; 2025] {
    let (ev, ev1, ev2, ev3, ev4) = (
        27.21_f64,
        27.21 / 2.0,
        27.21 / 4.0,
        27.21 / 8.0,
        27.21 / 16.0,
    );
    let mut output = [0.0; 2025];
    let r0 = input.r0;
    let da0 = input.da0;
    let db0 = input.db0;
    let qa0 = input.qa0;
    let qb0 = input.qb0;
    let dpa0 = input.dpa0;
    let dpb0 = input.dpb0;
    let dsa0 = input.dsa0;
    let dsb0 = input.dsb0;
    let dda0 = input.dda0;
    let ddb0 = input.ddb0;
    let rho0a = input.rho0a;
    let rho0b = input.rho0b;
    let rho1a = input.rho1a;
    let rho1b = input.rho1b;
    let rho2a = input.rho2a;
    let rho2b = input.rho2b;
    let rho3a = input.rho3a;
    let rho3b = input.rho3b;
    let rho4a = input.rho4a;
    let rho4b = input.rho4b;
    let rho5a = input.rho5a;
    let rho5b = input.rho5b;
    let rho6a = input.rho6a;
    let rho6b = input.rho6b;
    let rhoSS = (rho0b + rho0a).powi(2);
    let rhoSDD0 = (rho0b + rho3a).powi(2);
    let rhoSSP = (rho0b + rho1a).powi(2);
    let rhoSPD = (rho0b + rho4a).powi(2);
    let rhoSPP = (rho0b + rho2a).powi(2);
    let rhoSSD = (rho0b + rho5a).powi(2);
    let rhoSDD = (rho0b + rho6a).powi(2);
    let rhoD0SD = (rho0a + rho3b).powi(2);
    let rhoSPS = (rho0a + rho1b).powi(2);
    let rhoPDS = (rho0a + rho4b).powi(2);
    let rhoPPS = (rho0a + rho2b).powi(2);
    let rhoSDS = (rho0a + rho5b).powi(2);
    let rhoDDS = (rho0a + rho6b).powi(2);
    let rhoDD0DD0 = (rho3b + rho3a).powi(2);
    let rhoDD0SP = (rho3b + rho1a).powi(2);
    let rhoDD0PD = (rho3b + rho4a).powi(2);
    let rhoDD0PP = (rho3b + rho2a).powi(2);
    let rhoDD0SD = (rho3b + rho5a).powi(2);
    let rhoDD0DD = (rho3b + rho6a).powi(2);
    let rhoSPDD0 = (rho3a + rho1b).powi(2);
    let rhoPDDD0 = (rho3a + rho4b).powi(2);
    let rhoPPDD0 = (rho3a + rho2b).powi(2);
    let rhoSDDD0 = (rho3a + rho5b).powi(2);
    let rhoDDDD0 = (rho3a + rho6b).powi(2);
    let rhoSPSP = (rho1b + rho1a).powi(2);
    let rhoSPPD = (rho1b + rho4a).powi(2);
    let rhoPDPD = (rho4b + rho4a).powi(2);
    let rhoPDSP = (rho1a + rho4b).powi(2);
    let rhoSPPP = (rho1b + rho2a).powi(2);
    let rhoSPSD = (rho1b + rho5a).powi(2);
    let rhoSPDD = (rho1b + rho6a).powi(2);
    let rhoPDPP = (rho4b + rho2a).powi(2);
    let rhoPDSD = (rho4b + rho5a).powi(2);
    let rhoPDDD = (rho4b + rho6a).powi(2);
    let rhoPPSP = (rho1a + rho2b).powi(2);
    let rhoSDSP = (rho1a + rho5b).powi(2);
    let rhoDDSP = (rho1a + rho6b).powi(2);
    let rhoPPPD = (rho4a + rho2b).powi(2);
    let rhoSDPD = (rho4a + rho5b).powi(2);
    let rhoDDPD = (rho4a + rho6b).powi(2);
    let rhoPPPP = (rho2b + rho2a).powi(2);
    let rhoPPDD = (rho2b + rho6a).powi(2);
    let rhoSDDD = (rho5b + rho6a).powi(2);
    let rhoSDSD = (rho5b + rho5a).powi(2);
    let rhoDDDD = (rho6b + rho6a).powi(2);
    let rhoPPSD = (rho2b + rho5a).powi(2);
    let rhoDDPP = (rho2a + rho6b).powi(2);
    let rhoDDSD = (rho5a + rho6b).powi(2);
    let rhoSDPP = (rho2a + rho5b).powi(2);
    let qq = (ev / ((r0).powi(2) + rhoSS).sqrt());
    let Sq_DDq = (ev / ((r0).powi(2) + rhoD0SD).sqrt());
    let DDq_DDq = (ev / ((r0).powi(2) + rhoDD0DD0).sqrt());
    let DDq_Sq = (ev / ((r0).powi(2) + rhoSDD0).sqrt());
    let Sq_DPUz = (-((ev1 / ((r0 + dpb0).powi(2) + rhoPDS).sqrt())
        - (ev1 / ((r0 - dpb0).powi(2) + rhoPDS).sqrt())));
    let Sq_SPUz = (-((ev1 / ((r0 + db0).powi(2) + rhoSPS).sqrt())
        - (ev1 / ((r0 - db0).powi(2) + rhoSPS).sqrt())));
    let DDq_DPUz = (-((ev1 / ((r0 + dpb0).powi(2) + rhoPDDD0).sqrt())
        - (ev1 / ((r0 - dpb0).powi(2) + rhoPDDD0).sqrt())));
    let DDq_SPUz = (-((ev1 / ((r0 + db0).powi(2) + rhoSPDD0).sqrt())
        - (ev1 / ((r0 - db0).powi(2) + rhoSPDD0).sqrt())));
    let DPUz_Sq = ((ev1 / ((r0 + dpa0).powi(2) + rhoSPD).sqrt())
        - (ev1 / ((r0 - dpa0).powi(2) + rhoSPD).sqrt()));
    let SPUz_Sq = ((ev1 / ((r0 + da0).powi(2) + rhoSSP).sqrt())
        - (ev1 / ((r0 - da0).powi(2) + rhoSSP).sqrt()));
    let DPUz_DDq = ((ev1 / ((r0 + dpa0).powi(2) + rhoDD0PD).sqrt())
        - (ev1 / ((r0 - dpa0).powi(2) + rhoDD0PD).sqrt()));
    let SPUz_DDq = ((ev1 / ((r0 + da0).powi(2) + rhoDD0SP).sqrt())
        - (ev1 / ((r0 - da0).powi(2) + rhoDD0SP).sqrt()));
    let qa0 = (qa0 * (2.0_f64).sqrt());
    let qb0 = (qb0 * (2.0_f64).sqrt());
    let Sq_DDQtzx_onehalfQtxy = (((ev2 / ((r0 - ddb0).powi(2) + rhoDDS).sqrt())
        + (ev2 / ((r0 + ddb0).powi(2) + rhoDDS).sqrt()))
        - (ev1 / (((r0).powi(2) + (ddb0).powi(2)) + rhoDDS).sqrt()));
    let Sq_DSQtzx_onehalfQtxy = (((ev2 / ((r0 - dsb0).powi(2) + rhoSDS).sqrt())
        + (ev2 / ((r0 + dsb0).powi(2) + rhoSDS).sqrt()))
        - (ev1 / (((r0).powi(2) + (dsb0).powi(2)) + rhoSDS).sqrt()));
    let Sq_PPQtzx_onehalfQtxy = (((ev2 / ((r0 - (2.0_f64 * qb0)).powi(2) + rhoPPS).sqrt())
        + (ev2 / ((r0 + (2.0_f64 * qb0)).powi(2) + rhoPPS).sqrt()))
        - (ev1 / (((r0).powi(2) + (0.0_f64 * db0).powi(2)) + rhoPPS).sqrt()));
    let DDq_DDQtzx_onehalfQtxy = (((ev2 / ((r0 - ddb0).powi(2) + rhoDDDD0).sqrt())
        + (ev2 / ((r0 + ddb0).powi(2) + rhoDDDD0).sqrt()))
        - (ev1 / (((r0).powi(2) + (ddb0).powi(2)) + rhoDDDD0).sqrt()));
    let DDq_DSQtzx_onehalfQtxy = (((ev2 / ((r0 - dsb0).powi(2) + rhoSDDD0).sqrt())
        + (ev2 / ((r0 + dsb0).powi(2) + rhoSDDD0).sqrt()))
        - (ev1 / (((r0).powi(2) + (dsb0).powi(2)) + rhoSDDD0).sqrt()));
    let DDq_PPQtzx_onehalfQtxy = (((ev2 / ((r0 - qb0).powi(2) + rhoPPDD0).sqrt())
        + (ev2 / ((r0 + qb0).powi(2) + rhoPPDD0).sqrt()))
        - (ev1 / (((r0).powi(2) + (qb0).powi(2)) + rhoPPDD0).sqrt()));
    let DDQtzx_onehalfQtxy_Sq = (((ev2 / ((r0 - dda0).powi(2) + rhoSDD).sqrt())
        + (ev2 / ((r0 + dda0).powi(2) + rhoSDD).sqrt()))
        - (ev1 / (((r0).powi(2) + (dda0).powi(2)) + rhoSDD).sqrt()));
    let DSQtzx_onehalfQtxy_Sq = (((ev2 / ((r0 - dsa0).powi(2) + rhoSSD).sqrt())
        + (ev2 / ((r0 + dsa0).powi(2) + rhoSSD).sqrt()))
        - (ev1 / (((r0).powi(2) + (dsa0).powi(2)) + rhoSSD).sqrt()));
    let PPQtzx_onehalfQtxy_Sq = (((ev2 / ((r0 - qa0).powi(2) + rhoSPP).sqrt())
        + (ev2 / ((r0 + qa0).powi(2) + rhoSPP).sqrt()))
        - (ev1 / (((r0).powi(2) + (da0).powi(2)) + rhoSPP).sqrt()));
    let DDQtzx_onehalfQtxy_DDq = (((ev2 / ((r0 - dda0).powi(2) + rhoDD0DD).sqrt())
        + (ev2 / ((r0 + dda0).powi(2) + rhoDD0DD).sqrt()))
        - (ev1 / (((r0).powi(2) + (dda0).powi(2)) + rhoDD0DD).sqrt()));
    let DSQtzx_onehalfQtxy_DDq = (((ev2 / ((r0 - dsa0).powi(2) + rhoDD0SD).sqrt())
        + (ev2 / ((r0 + dsa0).powi(2) + rhoDD0SD).sqrt()))
        - (ev1 / (((r0).powi(2) + (dsa0).powi(2)) + rhoDD0SD).sqrt()));
    let PPQtzx_onehalfQtxy_DDq = (((ev2 / ((r0 - qa0).powi(2) + rhoDD0PP).sqrt())
        + (ev2 / ((r0 + qa0).powi(2) + rhoDD0PP).sqrt()))
        - (ev1 / (((r0).powi(2) + (qa0).powi(2)) + rhoDD0PP).sqrt()));
    let qa0 = (qa0 / (2.0_f64).sqrt());
    let qb0 = (qb0 / (2.0_f64).sqrt());
    let SPUpi_SPUpi = ((ev1 / (((r0).powi(2) + (da0 - qb0).powi(2)) + rhoSPSP).sqrt())
        - (ev1 / (((r0).powi(2) + (da0 + qb0).powi(2)) + rhoSPSP).sqrt()));
    let SPUpi_DPUpi = ((ev1 / (((r0).powi(2) + (da0 - dpb0).powi(2)) + rhoPDSP).sqrt())
        - (ev1 / (((r0).powi(2) + (da0 + dpb0).powi(2)) + rhoPDSP).sqrt()));
    let DPUpi_DPUpi = ((ev1 / (((r0).powi(2) + (dpa0 - dpb0).powi(2)) + rhoPDPD).sqrt())
        - (ev1 / (((r0).powi(2) + (dpa0 + dpb0).powi(2)) + rhoPDPD).sqrt()));
    let DPUpi_SPUpi = ((ev1 / (((r0).powi(2) + (db0 - dpa0).powi(2)) + rhoSPPD).sqrt())
        - (ev1 / (((r0).powi(2) + (db0 + dpa0).powi(2)) + rhoSPPD).sqrt()));
    let SPUz_SPUz = ((((ev2 / (((r0 + da0) - db0).powi(2) + rhoSPSP).sqrt())
        - (ev2 / (((r0 + da0) + db0).powi(2) + rhoSPSP).sqrt()))
        - (ev2 / (((r0 - da0) - db0).powi(2) + rhoSPSP).sqrt()))
        + (ev2 / (((r0 - da0) + db0).powi(2) + rhoSPSP).sqrt()));
    let SPUz_DPUz = ((((ev2 / (((r0 + da0) - dpb0).powi(2) + rhoPDSP).sqrt())
        - (ev2 / (((r0 + da0) + dpb0).powi(2) + rhoPDSP).sqrt()))
        - (ev2 / (((r0 - da0) - dpb0).powi(2) + rhoPDSP).sqrt()))
        + (ev2 / (((r0 - da0) + dpb0).powi(2) + rhoPDSP).sqrt()));
    let DPUz_DPUz = ((((ev2 / (((r0 + dpa0) - dpb0).powi(2) + rhoPDPD).sqrt())
        - (ev2 / (((r0 + dpa0) + dpb0).powi(2) + rhoPDPD).sqrt()))
        - (ev2 / (((r0 - dpa0) - dpb0).powi(2) + rhoPDPD).sqrt()))
        + (ev2 / (((r0 - dpa0) + dpb0).powi(2) + rhoPDPD).sqrt()));
    let DPUz_SPUz = ((((ev2 / (((r0 + db0) - dpa0).powi(2) + rhoSPPD).sqrt())
        - (ev2 / (((r0 + db0) + dpa0).powi(2) + rhoSPPD).sqrt()))
        - (ev2 / (((r0 - db0) - dpa0).powi(2) + rhoSPPD).sqrt()))
        + (ev2 / (((r0 - db0) + dpa0).powi(2) + rhoSPPD).sqrt()));
    let dsb0 = (dsb0 / (2.0_f64).sqrt());
    let dsa0 = (dsa0 / (2.0_f64).sqrt());
    let dda0 = (dda0 / (2.0_f64).sqrt());
    let ddb0 = (ddb0 / (2.0_f64).sqrt());
    let SPUpi_PPQpiz = (-(((((-ev2)
        / (((r0 - qb0).powi(2) + (da0 - qb0).powi(2)) + rhoPPSP).sqrt())
        + (ev2 / (((r0 - qb0).powi(2) + (da0 + qb0).powi(2)) + rhoPPSP).sqrt()))
        + (ev2 / (((r0 + qb0).powi(2) + (da0 - qb0).powi(2)) + rhoPPSP).sqrt()))
        - (ev2 / (((r0 + qb0).powi(2) + (da0 + qb0).powi(2)) + rhoPPSP).sqrt())));
    let SPUpi_DSQpiz = (-(((((-ev2)
        / (((r0 - dsb0).powi(2) + (da0 - dsb0).powi(2)) + rhoSDSP).sqrt())
        + (ev2 / (((r0 - dsb0).powi(2) + (da0 + dsb0).powi(2)) + rhoSDSP).sqrt()))
        + (ev2 / (((r0 + dsb0).powi(2) + (da0 - dsb0).powi(2)) + rhoSDSP).sqrt()))
        - (ev2 / (((r0 + dsb0).powi(2) + (da0 + dsb0).powi(2)) + rhoSDSP).sqrt())));
    let SPUpi_DDQpiz = (-(((((-ev2)
        / (((r0 - ddb0).powi(2) + (da0 - ddb0).powi(2)) + rhoDDSP).sqrt())
        + (ev2 / (((r0 - ddb0).powi(2) + (da0 + ddb0).powi(2)) + rhoDDSP).sqrt()))
        + (ev2 / (((r0 + ddb0).powi(2) + (da0 - ddb0).powi(2)) + rhoDDSP).sqrt()))
        - (ev2 / (((r0 + ddb0).powi(2) + (da0 + ddb0).powi(2)) + rhoDDSP).sqrt())));
    let DPUpi_PPQpiz = (-(((((-ev2)
        / (((r0 - qb0).powi(2) + (dpa0 - qb0).powi(2)) + rhoPPPD).sqrt())
        + (ev2 / (((r0 - qb0).powi(2) + (dpa0 + qb0).powi(2)) + rhoPPPD).sqrt()))
        + (ev2 / (((r0 + qb0).powi(2) + (dpa0 - qb0).powi(2)) + rhoPPPD).sqrt()))
        - (ev2 / (((r0 + qb0).powi(2) + (dpa0 + qb0).powi(2)) + rhoPPPD).sqrt())));
    let DPUpi_DSQpiz = (-(((((-ev2)
        / (((r0 - dsb0).powi(2) + (dpa0 - dsb0).powi(2)) + rhoSDPD).sqrt())
        + (ev2 / (((r0 - dsb0).powi(2) + (dpa0 + dsb0).powi(2)) + rhoSDPD).sqrt()))
        + (ev2 / (((r0 + dsb0).powi(2) + (dpa0 - dsb0).powi(2)) + rhoSDPD).sqrt()))
        - (ev2 / (((r0 + dsb0).powi(2) + (dpa0 + dsb0).powi(2)) + rhoSDPD).sqrt())));
    let DPUpi_DDQpiz = (-(((((-ev2)
        / (((r0 - ddb0).powi(2) + (dpa0 - ddb0).powi(2)) + rhoDDPD).sqrt())
        + (ev2 / (((r0 - ddb0).powi(2) + (dpa0 + ddb0).powi(2)) + rhoDDPD).sqrt()))
        + (ev2 / (((r0 + ddb0).powi(2) + (dpa0 - ddb0).powi(2)) + rhoDDPD).sqrt()))
        - (ev2 / (((r0 + ddb0).powi(2) + (dpa0 + ddb0).powi(2)) + rhoDDPD).sqrt())));
    let PPQpiz_SPUpi = (((((-ev2)
        / (((r0 - qa0).powi(2) + (db0 - qa0).powi(2)) + rhoSPPP).sqrt())
        + (ev2 / (((r0 - qa0).powi(2) + (db0 + qa0).powi(2)) + rhoSPPP).sqrt()))
        + (ev2 / (((r0 + qa0).powi(2) + (db0 - qa0).powi(2)) + rhoSPPP).sqrt()))
        - (ev2 / (((r0 + qa0).powi(2) + (db0 + qa0).powi(2)) + rhoSPPP).sqrt()));
    let DSQpiz_SPUpi = (((((-ev2)
        / (((r0 - dsa0).powi(2) + (db0 - dsa0).powi(2)) + rhoSPSD).sqrt())
        + (ev2 / (((r0 - dsa0).powi(2) + (db0 + dsa0).powi(2)) + rhoSPSD).sqrt()))
        + (ev2 / (((r0 + dsa0).powi(2) + (db0 - dsa0).powi(2)) + rhoSPSD).sqrt()))
        - (ev2 / (((r0 + dsa0).powi(2) + (db0 + dsa0).powi(2)) + rhoSPSD).sqrt()));
    let DDQpiz_SPUpi = (((((-ev2)
        / (((r0 - dda0).powi(2) + (db0 - dda0).powi(2)) + rhoSPDD).sqrt())
        + (ev2 / (((r0 - dda0).powi(2) + (db0 + dda0).powi(2)) + rhoSPDD).sqrt()))
        + (ev2 / (((r0 + dda0).powi(2) + (db0 - dda0).powi(2)) + rhoSPDD).sqrt()))
        - (ev2 / (((r0 + dda0).powi(2) + (db0 + dda0).powi(2)) + rhoSPDD).sqrt()));
    let PPQpiz_DPUpi = (((((-ev2)
        / (((r0 - qa0).powi(2) + (dpb0 - qa0).powi(2)) + rhoPDPP).sqrt())
        + (ev2 / (((r0 - qa0).powi(2) + (dpb0 + qa0).powi(2)) + rhoPDPP).sqrt()))
        + (ev2 / (((r0 + qa0).powi(2) + (dpb0 - qa0).powi(2)) + rhoPDPP).sqrt()))
        - (ev2 / (((r0 + qa0).powi(2) + (dpb0 + qa0).powi(2)) + rhoPDPP).sqrt()));
    let DSQpiz_DPUpi = (((((-ev2)
        / (((r0 - dsa0).powi(2) + (dpb0 - dsa0).powi(2)) + rhoPDSD).sqrt())
        + (ev2 / (((r0 - dsa0).powi(2) + (dpb0 + dsa0).powi(2)) + rhoPDSD).sqrt()))
        + (ev2 / (((r0 + dsa0).powi(2) + (dpb0 - dsa0).powi(2)) + rhoPDSD).sqrt()))
        - (ev2 / (((r0 + dsa0).powi(2) + (dpb0 + dsa0).powi(2)) + rhoPDSD).sqrt()));
    let DDQpiz_DPUpi = (((((-ev2)
        / (((r0 - dda0).powi(2) + (dpb0 - dda0).powi(2)) + rhoPDDD).sqrt())
        + (ev2 / (((r0 - dda0).powi(2) + (dpb0 + dda0).powi(2)) + rhoPDDD).sqrt()))
        + (ev2 / (((r0 + dda0).powi(2) + (dpb0 - dda0).powi(2)) + rhoPDDD).sqrt()))
        - (ev2 / (((r0 + dda0).powi(2) + (dpb0 + dda0).powi(2)) + rhoPDDD).sqrt()));
    let dsb0 = (dsb0 * (2.0_f64).sqrt());
    let dsa0 = (dsa0 * (2.0_f64).sqrt());
    let dda0 = (dda0 * (2.0_f64).sqrt());
    let ddb0 = (ddb0 * (2.0_f64).sqrt());
    let qa0 = (qa0 * (2.0_f64).sqrt());
    let qb0 = (qb0 * (2.0_f64).sqrt());
    let SPUz_PPQtzx_onehalfQtxy = (((((((-ev3)
        / (((r0 - da0) - ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPPSP).sqrt())
        - (ev3 / (((r0 - da0) + ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPPSP).sqrt()))
        + (ev3 / (((r0 + da0) - ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPPSP).sqrt()))
        + (ev3 / (((r0 + da0) + ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPPSP).sqrt()))
        + (ev2 / (((r0 - da0).powi(2) + ((1.0_f64).sqrt() * qb0).powi(2)) + rhoPPSP).sqrt()))
        - (ev2 / (((r0 + da0).powi(2) + ((1.0_f64).sqrt() * qb0).powi(2)) + rhoPPSP).sqrt()));
    let SPUz_DSQtzx_onehalfQtxy = (((((((-ev3)
        / (((r0 - da0) - ((1.0_f64).sqrt() * dsb0)).powi(2) + rhoSDSP).sqrt())
        - (ev3 / (((r0 - da0) + ((1.0_f64).sqrt() * dsb0)).powi(2) + rhoSDSP).sqrt()))
        + (ev3 / (((r0 + da0) - ((1.0_f64).sqrt() * dsb0)).powi(2) + rhoSDSP).sqrt()))
        + (ev3 / (((r0 + da0) + ((1.0_f64).sqrt() * dsb0)).powi(2) + rhoSDSP).sqrt()))
        + (ev2 / (((r0 - da0).powi(2) + ((1.0_f64).sqrt() * dsb0).powi(2)) + rhoSDSP).sqrt()))
        - (ev2 / (((r0 + da0).powi(2) + ((1.0_f64).sqrt() * dsb0).powi(2)) + rhoSDSP).sqrt()));
    let SPUz_DDQtzx_onehalfQtxy = (((((((-ev3)
        / (((r0 - da0) - ((1.0_f64).sqrt() * ddb0)).powi(2) + rhoDDSP).sqrt())
        - (ev3 / (((r0 - da0) + ((1.0_f64).sqrt() * ddb0)).powi(2) + rhoDDSP).sqrt()))
        + (ev3 / (((r0 + da0) - ((1.0_f64).sqrt() * ddb0)).powi(2) + rhoDDSP).sqrt()))
        + (ev3 / (((r0 + da0) + ((1.0_f64).sqrt() * ddb0)).powi(2) + rhoDDSP).sqrt()))
        + (ev2 / (((r0 - da0).powi(2) + ((1.0_f64).sqrt() * ddb0).powi(2)) + rhoDDSP).sqrt()))
        - (ev2 / (((r0 + da0).powi(2) + ((1.0_f64).sqrt() * ddb0).powi(2)) + rhoDDSP).sqrt()));
    let DPUz_PPQtzx_onehalfQtxy = (((((((-ev3)
        / (((r0 - dpa0) - ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPPPD).sqrt())
        - (ev3 / (((r0 - dpa0) + ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPPPD).sqrt()))
        + (ev3 / (((r0 + dpa0) - ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPPPD).sqrt()))
        + (ev3 / (((r0 + dpa0) + ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPPPD).sqrt()))
        + (ev2 / (((r0 - dpa0).powi(2) + ((1.0_f64).sqrt() * qb0).powi(2)) + rhoPPPD).sqrt()))
        - (ev2 / (((r0 + dpa0).powi(2) + ((1.0_f64).sqrt() * qb0).powi(2)) + rhoPPPD).sqrt()));
    let DPUz_DSQtzx_onehalfQtxy = (((((((-ev3)
        / (((r0 - dpa0) - ((1.0_f64).sqrt() * dsb0)).powi(2) + rhoSDPD).sqrt())
        - (ev3 / (((r0 - dpa0) + ((1.0_f64).sqrt() * dsb0)).powi(2) + rhoSDPD).sqrt()))
        + (ev3 / (((r0 + dpa0) - ((1.0_f64).sqrt() * dsb0)).powi(2) + rhoSDPD).sqrt()))
        + (ev3 / (((r0 + dpa0) + ((1.0_f64).sqrt() * dsb0)).powi(2) + rhoSDPD).sqrt()))
        + (ev2 / (((r0 - dpa0).powi(2) + ((1.0_f64).sqrt() * dsb0).powi(2)) + rhoSDPD).sqrt()))
        - (ev2 / (((r0 + dpa0).powi(2) + ((1.0_f64).sqrt() * dsb0).powi(2)) + rhoSDPD).sqrt()));
    let DPUz_DDQtzx_onehalfQtxy = (((((((-ev3)
        / (((r0 - dpa0) - ((1.0_f64).sqrt() * ddb0)).powi(2) + rhoDDPD).sqrt())
        - (ev3 / (((r0 - dpa0) + ((1.0_f64).sqrt() * ddb0)).powi(2) + rhoDDPD).sqrt()))
        + (ev3 / (((r0 + dpa0) - ((1.0_f64).sqrt() * ddb0)).powi(2) + rhoDDPD).sqrt()))
        + (ev3 / (((r0 + dpa0) + ((1.0_f64).sqrt() * ddb0)).powi(2) + rhoDDPD).sqrt()))
        + (ev2 / (((r0 - dpa0).powi(2) + ((1.0_f64).sqrt() * ddb0).powi(2)) + rhoDDPD).sqrt()))
        - (ev2 / (((r0 + dpa0).powi(2) + ((1.0_f64).sqrt() * ddb0).powi(2)) + rhoDDPD).sqrt()));
    let PPQtzx_onehalfQtxy_SPUz = (-(((((((-ev3)
        / (((r0 - db0) - ((1.0_f64).sqrt() * qa0)).powi(2) + rhoSPPP).sqrt())
        - (ev3 / (((r0 - db0) + ((1.0_f64).sqrt() * qa0)).powi(2) + rhoSPPP).sqrt()))
        + (ev3 / (((r0 + db0) - ((1.0_f64).sqrt() * qa0)).powi(2) + rhoSPPP).sqrt()))
        + (ev3 / (((r0 + db0) + ((1.0_f64).sqrt() * qa0)).powi(2) + rhoSPPP).sqrt()))
        + (ev2 / (((r0 - db0).powi(2) + ((1.0_f64).sqrt() * qa0).powi(2)) + rhoSPPP).sqrt()))
        - (ev2 / (((r0 + db0).powi(2) + ((1.0_f64).sqrt() * qa0).powi(2)) + rhoSPPP).sqrt())));
    let DSQtzx_onehalfQtxy_SPUz = (-(((((((-ev3)
        / (((r0 - db0) - ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoSPSD).sqrt())
        - (ev3 / (((r0 - db0) + ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoSPSD).sqrt()))
        + (ev3 / (((r0 + db0) - ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoSPSD).sqrt()))
        + (ev3 / (((r0 + db0) + ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoSPSD).sqrt()))
        + (ev2 / (((r0 - db0).powi(2) + ((1.0_f64).sqrt() * dsa0).powi(2)) + rhoSPSD).sqrt()))
        - (ev2 / (((r0 + db0).powi(2) + ((1.0_f64).sqrt() * dsa0).powi(2)) + rhoSPSD).sqrt())));
    let DDQtzx_onehalfQtxy_SPUz = (-(((((((-ev3)
        / (((r0 - db0) - ((1.0_f64).sqrt() * dda0)).powi(2) + rhoSPDD).sqrt())
        - (ev3 / (((r0 - db0) + ((1.0_f64).sqrt() * dda0)).powi(2) + rhoSPDD).sqrt()))
        + (ev3 / (((r0 + db0) - ((1.0_f64).sqrt() * dda0)).powi(2) + rhoSPDD).sqrt()))
        + (ev3 / (((r0 + db0) + ((1.0_f64).sqrt() * dda0)).powi(2) + rhoSPDD).sqrt()))
        + (ev2 / (((r0 - db0).powi(2) + ((1.0_f64).sqrt() * dda0).powi(2)) + rhoSPDD).sqrt()))
        - (ev2 / (((r0 + db0).powi(2) + ((1.0_f64).sqrt() * dda0).powi(2)) + rhoSPDD).sqrt())));
    let PPQtzx_onehalfQtxy_DPUz = (-(((((((-ev3)
        / (((r0 - dpb0) - ((1.0_f64).sqrt() * qa0)).powi(2) + rhoPDPP).sqrt())
        - (ev3 / (((r0 - dpb0) + ((1.0_f64).sqrt() * qa0)).powi(2) + rhoPDPP).sqrt()))
        + (ev3 / (((r0 + dpb0) - ((1.0_f64).sqrt() * qa0)).powi(2) + rhoPDPP).sqrt()))
        + (ev3 / (((r0 + dpb0) + ((1.0_f64).sqrt() * qa0)).powi(2) + rhoPDPP).sqrt()))
        + (ev2 / (((r0 - dpb0).powi(2) + ((1.0_f64).sqrt() * qa0).powi(2)) + rhoPDPP).sqrt()))
        - (ev2 / (((r0 + dpb0).powi(2) + ((1.0_f64).sqrt() * qa0).powi(2)) + rhoPDPP).sqrt())));
    let DSQtzx_onehalfQtxy_DPUz = (-(((((((-ev3)
        / (((r0 - dpb0) - ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoPDSD).sqrt())
        - (ev3 / (((r0 - dpb0) + ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoPDSD).sqrt()))
        + (ev3 / (((r0 + dpb0) - ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoPDSD).sqrt()))
        + (ev3 / (((r0 + dpb0) + ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoPDSD).sqrt()))
        + (ev2 / (((r0 - dpb0).powi(2) + ((1.0_f64).sqrt() * dsa0).powi(2)) + rhoPDSD).sqrt()))
        - (ev2 / (((r0 + dpb0).powi(2) + ((1.0_f64).sqrt() * dsa0).powi(2)) + rhoPDSD).sqrt())));
    let DDQtzx_onehalfQtxy_DPUz = (-(((((((-ev3)
        / (((r0 - dpb0) - ((1.0_f64).sqrt() * dda0)).powi(2) + rhoPDDD).sqrt())
        - (ev3 / (((r0 - dpb0) + ((1.0_f64).sqrt() * dda0)).powi(2) + rhoPDDD).sqrt()))
        + (ev3 / (((r0 + dpb0) - ((1.0_f64).sqrt() * dda0)).powi(2) + rhoPDDD).sqrt()))
        + (ev3 / (((r0 + dpb0) + ((1.0_f64).sqrt() * dda0)).powi(2) + rhoPDDD).sqrt()))
        + (ev2 / (((r0 - dpb0).powi(2) + ((1.0_f64).sqrt() * dda0).powi(2)) + rhoPDDD).sqrt()))
        - (ev2 / (((r0 + dpb0).powi(2) + ((1.0_f64).sqrt() * dda0).powi(2)) + rhoPDDD).sqrt())));
    let qa0 = (qa0 / (2.0_f64).sqrt());
    let qb0 = (qb0 / (2.0_f64).sqrt());
    let qa0 = (qa0 * (2.0_f64).sqrt());
    let qb0 = (qb0 * (2.0_f64).sqrt());
    let PPQtzx_onehalfQtxy_PPQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt())
        + (ev3 / (((r0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / (((r0 + qb0).powi(2) + (qa0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / (((r0 - qb0).powi(2) + (qa0).powi(2)) + rhoPPPP).sqrt()))
        + (ev4 / (((r0 - qb0) + qa0).powi(2) + rhoPPPP).sqrt()))
        + (ev4 / (((r0 + qb0) - qa0).powi(2) + rhoPPPP).sqrt()))
        + (ev4 / (((r0 + qb0) + qa0).powi(2) + rhoPPPP).sqrt()))
        + (ev4 / (((r0 - qb0) - qa0).powi(2) + rhoPPPP).sqrt()))
        - (ev3 / (((r0 - qa0).powi(2) + (qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / (((r0 + qa0).powi(2) + (qb0).powi(2)) + rhoPPPP).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt())
                + (ev2 / (((r0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
                - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (qb0).powi(2)) + rhoPPPP).sqrt()))));
    let PPQtzx_onehalfQtxy_DSQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (qa0 - dsb0).powi(2)) + rhoSDPP).sqrt())
        + (ev3 / (((r0).powi(2) + (qa0 + dsb0).powi(2)) + rhoSDPP).sqrt()))
        - (ev3 / (((r0 + dsb0).powi(2) + (qa0).powi(2)) + rhoSDPP).sqrt()))
        - (ev3 / (((r0 - dsb0).powi(2) + (qa0).powi(2)) + rhoSDPP).sqrt()))
        + (ev4 / (((r0 - dsb0) + qa0).powi(2) + rhoSDPP).sqrt()))
        + (ev4 / (((r0 + dsb0) - qa0).powi(2) + rhoSDPP).sqrt()))
        + (ev4 / (((r0 + dsb0) + qa0).powi(2) + rhoSDPP).sqrt()))
        + (ev4 / (((r0 - dsb0) - qa0).powi(2) + rhoSDPP).sqrt()))
        - (ev3 / (((r0 - qa0).powi(2) + (dsb0).powi(2)) + rhoSDPP).sqrt()))
        - (ev3 / (((r0 + qa0).powi(2) + (dsb0).powi(2)) + rhoSDPP).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (qa0 - dsb0).powi(2)) + rhoSDPP).sqrt())
                + (ev2 / (((r0).powi(2) + (qa0 + dsb0).powi(2)) + rhoSDPP).sqrt()))
                - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (dsb0).powi(2)) + rhoSDPP).sqrt()))));
    let PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (qa0 - ddb0).powi(2)) + rhoDDPP).sqrt())
        + (ev3 / (((r0).powi(2) + (qa0 + ddb0).powi(2)) + rhoDDPP).sqrt()))
        - (ev3 / (((r0 + ddb0).powi(2) + (qa0).powi(2)) + rhoDDPP).sqrt()))
        - (ev3 / (((r0 - ddb0).powi(2) + (qa0).powi(2)) + rhoDDPP).sqrt()))
        + (ev4 / (((r0 - ddb0) + qa0).powi(2) + rhoDDPP).sqrt()))
        + (ev4 / (((r0 + ddb0) - qa0).powi(2) + rhoDDPP).sqrt()))
        + (ev4 / (((r0 + ddb0) + qa0).powi(2) + rhoDDPP).sqrt()))
        + (ev4 / (((r0 - ddb0) - qa0).powi(2) + rhoDDPP).sqrt()))
        - (ev3 / (((r0 - qa0).powi(2) + (ddb0).powi(2)) + rhoDDPP).sqrt()))
        - (ev3 / (((r0 + qa0).powi(2) + (ddb0).powi(2)) + rhoDDPP).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (qa0 - ddb0).powi(2)) + rhoDDPP).sqrt())
                + (ev2 / (((r0).powi(2) + (qa0 + ddb0).powi(2)) + rhoDDPP).sqrt()))
                - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (ddb0).powi(2)) + rhoDDPP).sqrt()))));
    let DSQtzx_onehalfQtxy_DDQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (dsa0 - ddb0).powi(2)) + rhoDDSD).sqrt())
        + (ev3 / (((r0).powi(2) + (dsa0 + ddb0).powi(2)) + rhoDDSD).sqrt()))
        - (ev3 / (((r0 + ddb0).powi(2) + (dsa0).powi(2)) + rhoDDSD).sqrt()))
        - (ev3 / (((r0 - ddb0).powi(2) + (dsa0).powi(2)) + rhoDDSD).sqrt()))
        + (ev4 / (((r0 - ddb0) + dsa0).powi(2) + rhoDDSD).sqrt()))
        + (ev4 / (((r0 + ddb0) - dsa0).powi(2) + rhoDDSD).sqrt()))
        + (ev4 / (((r0 + ddb0) + dsa0).powi(2) + rhoDDSD).sqrt()))
        + (ev4 / (((r0 - ddb0) - dsa0).powi(2) + rhoDDSD).sqrt()))
        - (ev3 / (((r0 - dsa0).powi(2) + (ddb0).powi(2)) + rhoDDSD).sqrt()))
        - (ev3 / (((r0 + dsa0).powi(2) + (ddb0).powi(2)) + rhoDDSD).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (dsa0 - ddb0).powi(2)) + rhoDDSD).sqrt())
                + (ev2 / (((r0).powi(2) + (dsa0 + ddb0).powi(2)) + rhoDDSD).sqrt()))
                - (ev1 / ((((r0).powi(2) + (dsa0).powi(2)) + (ddb0).powi(2)) + rhoDDSD).sqrt()))));
    let DSQtzx_onehalfQtxy_DSQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (dsa0 - dsb0).powi(2)) + rhoSDSD).sqrt())
        + (ev3 / (((r0).powi(2) + (dsa0 + dsb0).powi(2)) + rhoSDSD).sqrt()))
        - (ev3 / (((r0 + dsb0).powi(2) + (dsa0).powi(2)) + rhoSDSD).sqrt()))
        - (ev3 / (((r0 - dsb0).powi(2) + (dsa0).powi(2)) + rhoSDSD).sqrt()))
        + (ev4 / (((r0 - dsb0) + dsa0).powi(2) + rhoSDSD).sqrt()))
        + (ev4 / (((r0 + dsb0) - dsa0).powi(2) + rhoSDSD).sqrt()))
        + (ev4 / (((r0 + dsb0) + dsa0).powi(2) + rhoSDSD).sqrt()))
        + (ev4 / (((r0 - dsb0) - dsa0).powi(2) + rhoSDSD).sqrt()))
        - (ev3 / (((r0 - dsa0).powi(2) + (dsb0).powi(2)) + rhoSDSD).sqrt()))
        - (ev3 / (((r0 + dsa0).powi(2) + (dsb0).powi(2)) + rhoSDSD).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (dsa0 - dsb0).powi(2)) + rhoSDSD).sqrt())
                + (ev2 / (((r0).powi(2) + (dsa0 + dsb0).powi(2)) + rhoSDSD).sqrt()))
                - (ev1 / ((((r0).powi(2) + (dsa0).powi(2)) + (dsb0).powi(2)) + rhoSDSD).sqrt()))));
    let DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (dda0 - ddb0).powi(2)) + rhoDDDD).sqrt())
        + (ev3 / (((r0).powi(2) + (dda0 + ddb0).powi(2)) + rhoDDDD).sqrt()))
        - (ev3 / (((r0 + ddb0).powi(2) + (dda0).powi(2)) + rhoDDDD).sqrt()))
        - (ev3 / (((r0 - ddb0).powi(2) + (dda0).powi(2)) + rhoDDDD).sqrt()))
        + (ev4 / (((r0 - ddb0) + dda0).powi(2) + rhoDDDD).sqrt()))
        + (ev4 / (((r0 + ddb0) - dda0).powi(2) + rhoDDDD).sqrt()))
        + (ev4 / (((r0 + ddb0) + dda0).powi(2) + rhoDDDD).sqrt()))
        + (ev4 / (((r0 - ddb0) - dda0).powi(2) + rhoDDDD).sqrt()))
        - (ev3 / (((r0 - dda0).powi(2) + (ddb0).powi(2)) + rhoDDDD).sqrt()))
        - (ev3 / (((r0 + dda0).powi(2) + (ddb0).powi(2)) + rhoDDDD).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (dda0 - ddb0).powi(2)) + rhoDDDD).sqrt())
                + (ev2 / (((r0).powi(2) + (dda0 + ddb0).powi(2)) + rhoDDDD).sqrt()))
                - (ev1 / ((((r0).powi(2) + (dda0).powi(2)) + (ddb0).powi(2)) + rhoDDDD).sqrt()))));
    let DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt())
        + (ev3 / (((r0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / (((r0 + dsa0).powi(2) + (qb0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / (((r0 - dsa0).powi(2) + (qb0).powi(2)) + rhoPPSD).sqrt()))
        + (ev4 / (((r0 - dsa0) + qb0).powi(2) + rhoPPSD).sqrt()))
        + (ev4 / (((r0 + dsa0) - qb0).powi(2) + rhoPPSD).sqrt()))
        + (ev4 / (((r0 + dsa0) + qb0).powi(2) + rhoPPSD).sqrt()))
        + (ev4 / (((r0 - dsa0) - qb0).powi(2) + rhoPPSD).sqrt()))
        - (ev3 / (((r0 - qb0).powi(2) + (dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / (((r0 + qb0).powi(2) + (dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt())
                + (ev2 / (((r0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
                - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dsa0).powi(2)) + rhoPPSD).sqrt()))));
    let DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt())
        + (ev3 / (((r0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / (((r0 + dda0).powi(2) + (qb0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / (((r0 - dda0).powi(2) + (qb0).powi(2)) + rhoPPDD).sqrt()))
        + (ev4 / (((r0 - dda0) + qb0).powi(2) + rhoPPDD).sqrt()))
        + (ev4 / (((r0 + dda0) - qb0).powi(2) + rhoPPDD).sqrt()))
        + (ev4 / (((r0 + dda0) + qb0).powi(2) + rhoPPDD).sqrt()))
        + (ev4 / (((r0 - dda0) - qb0).powi(2) + rhoPPDD).sqrt()))
        - (ev3 / (((r0 - qb0).powi(2) + (dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / (((r0 + qb0).powi(2) + (dda0).powi(2)) + rhoPPDD).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt())
                + (ev2 / (((r0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
                - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dda0).powi(2)) + rhoPPDD).sqrt()))));
    let DDQtzx_onehalfQtxy_DSQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (dsb0 - dda0).powi(2)) + rhoSDDD).sqrt())
        + (ev3 / (((r0).powi(2) + (dsb0 + dda0).powi(2)) + rhoSDDD).sqrt()))
        - (ev3 / (((r0 + dda0).powi(2) + (dsb0).powi(2)) + rhoSDDD).sqrt()))
        - (ev3 / (((r0 - dda0).powi(2) + (dsb0).powi(2)) + rhoSDDD).sqrt()))
        + (ev4 / (((r0 - dda0) + dsb0).powi(2) + rhoSDDD).sqrt()))
        + (ev4 / (((r0 + dda0) - dsb0).powi(2) + rhoSDDD).sqrt()))
        + (ev4 / (((r0 + dda0) + dsb0).powi(2) + rhoSDDD).sqrt()))
        + (ev4 / (((r0 - dda0) - dsb0).powi(2) + rhoSDDD).sqrt()))
        - (ev3 / (((r0 - dsb0).powi(2) + (dda0).powi(2)) + rhoSDDD).sqrt()))
        - (ev3 / (((r0 + dsb0).powi(2) + (dda0).powi(2)) + rhoSDDD).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (dsb0 - dda0).powi(2)) + rhoSDDD).sqrt())
                + (ev2 / (((r0).powi(2) + (dsb0 + dda0).powi(2)) + rhoSDDD).sqrt()))
                - (ev1 / ((((r0).powi(2) + (dsb0).powi(2)) + (dda0).powi(2)) + rhoSDDD).sqrt()))));
    let qa0 = (qa0 / (2.0_f64).sqrt());
    let qb0 = (qb0 / (2.0_f64).sqrt());
    let dsb0 = (dsb0 / (2.0_f64).sqrt());
    let dsa0 = (dsa0 / (2.0_f64).sqrt());
    let dda0 = (dda0 / (2.0_f64).sqrt());
    let ddb0 = (ddb0 / (2.0_f64).sqrt());
    let PPQpiz_PPQpiz = ((((((((ev3
        / ((((r0 + qa0) - qb0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt())
        - (ev3 / ((((r0 + qa0) - qb0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / ((((r0 + qa0) + qb0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt()))
        + (ev3 / ((((r0 + qa0) + qb0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / ((((r0 - qa0) - qb0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt()))
        + (ev3 / ((((r0 - qa0) - qb0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        + (ev3 / ((((r0 - qa0) + qb0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / ((((r0 - qa0) + qb0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()));
    let PPQpiz_DSQpiz = ((((((((ev3
        / ((((r0 + qa0) - dsb0).powi(2) + (qa0 - dsb0).powi(2)) + rhoSDPP).sqrt())
        - (ev3 / ((((r0 + qa0) - dsb0).powi(2) + (qa0 + dsb0).powi(2)) + rhoSDPP).sqrt()))
        - (ev3 / ((((r0 + qa0) + dsb0).powi(2) + (qa0 - dsb0).powi(2)) + rhoSDPP).sqrt()))
        + (ev3 / ((((r0 + qa0) + dsb0).powi(2) + (qa0 + dsb0).powi(2)) + rhoSDPP).sqrt()))
        - (ev3 / ((((r0 - qa0) - dsb0).powi(2) + (qa0 - dsb0).powi(2)) + rhoSDPP).sqrt()))
        + (ev3 / ((((r0 - qa0) - dsb0).powi(2) + (qa0 + dsb0).powi(2)) + rhoSDPP).sqrt()))
        + (ev3 / ((((r0 - qa0) + dsb0).powi(2) + (qa0 - dsb0).powi(2)) + rhoSDPP).sqrt()))
        - (ev3 / ((((r0 - qa0) + dsb0).powi(2) + (qa0 + dsb0).powi(2)) + rhoSDPP).sqrt()));
    let PPQpiz_DDQpiz = ((((((((ev3
        / ((((r0 + qa0) - ddb0).powi(2) + (qa0 - ddb0).powi(2)) + rhoDDPP).sqrt())
        - (ev3 / ((((r0 + qa0) - ddb0).powi(2) + (qa0 + ddb0).powi(2)) + rhoDDPP).sqrt()))
        - (ev3 / ((((r0 + qa0) + ddb0).powi(2) + (qa0 - ddb0).powi(2)) + rhoDDPP).sqrt()))
        + (ev3 / ((((r0 + qa0) + ddb0).powi(2) + (qa0 + ddb0).powi(2)) + rhoDDPP).sqrt()))
        - (ev3 / ((((r0 - qa0) - ddb0).powi(2) + (qa0 - ddb0).powi(2)) + rhoDDPP).sqrt()))
        + (ev3 / ((((r0 - qa0) - ddb0).powi(2) + (qa0 + ddb0).powi(2)) + rhoDDPP).sqrt()))
        + (ev3 / ((((r0 - qa0) + ddb0).powi(2) + (qa0 - ddb0).powi(2)) + rhoDDPP).sqrt()))
        - (ev3 / ((((r0 - qa0) + ddb0).powi(2) + (qa0 + ddb0).powi(2)) + rhoDDPP).sqrt()));
    let DSQpiz_DSQpiz = ((((((((ev3
        / ((((r0 + dsa0) - dsb0).powi(2) + (dsa0 - dsb0).powi(2)) + rhoSDSD).sqrt())
        - (ev3 / ((((r0 + dsa0) - dsb0).powi(2) + (dsa0 + dsb0).powi(2)) + rhoSDSD).sqrt()))
        - (ev3 / ((((r0 + dsa0) + dsb0).powi(2) + (dsa0 - dsb0).powi(2)) + rhoSDSD).sqrt()))
        + (ev3 / ((((r0 + dsa0) + dsb0).powi(2) + (dsa0 + dsb0).powi(2)) + rhoSDSD).sqrt()))
        - (ev3 / ((((r0 - dsa0) - dsb0).powi(2) + (dsa0 - dsb0).powi(2)) + rhoSDSD).sqrt()))
        + (ev3 / ((((r0 - dsa0) - dsb0).powi(2) + (dsa0 + dsb0).powi(2)) + rhoSDSD).sqrt()))
        + (ev3 / ((((r0 - dsa0) + dsb0).powi(2) + (dsa0 - dsb0).powi(2)) + rhoSDSD).sqrt()))
        - (ev3 / ((((r0 - dsa0) + dsb0).powi(2) + (dsa0 + dsb0).powi(2)) + rhoSDSD).sqrt()));
    let DSQpiz_DDQpiz = ((((((((ev3
        / ((((r0 + dsa0) - ddb0).powi(2) + (dsa0 - ddb0).powi(2)) + rhoDDSD).sqrt())
        - (ev3 / ((((r0 + dsa0) - ddb0).powi(2) + (dsa0 + ddb0).powi(2)) + rhoDDSD).sqrt()))
        - (ev3 / ((((r0 + dsa0) + ddb0).powi(2) + (dsa0 - ddb0).powi(2)) + rhoDDSD).sqrt()))
        + (ev3 / ((((r0 + dsa0) + ddb0).powi(2) + (dsa0 + ddb0).powi(2)) + rhoDDSD).sqrt()))
        - (ev3 / ((((r0 - dsa0) - ddb0).powi(2) + (dsa0 - ddb0).powi(2)) + rhoDDSD).sqrt()))
        + (ev3 / ((((r0 - dsa0) - ddb0).powi(2) + (dsa0 + ddb0).powi(2)) + rhoDDSD).sqrt()))
        + (ev3 / ((((r0 - dsa0) + ddb0).powi(2) + (dsa0 - ddb0).powi(2)) + rhoDDSD).sqrt()))
        - (ev3 / ((((r0 - dsa0) + ddb0).powi(2) + (dsa0 + ddb0).powi(2)) + rhoDDSD).sqrt()));
    let DDQpiz_DDQpiz = ((((((((ev3
        / ((((r0 + dda0) - ddb0).powi(2) + (dda0 - ddb0).powi(2)) + rhoDDDD).sqrt())
        - (ev3 / ((((r0 + dda0) - ddb0).powi(2) + (dda0 + ddb0).powi(2)) + rhoDDDD).sqrt()))
        - (ev3 / ((((r0 + dda0) + ddb0).powi(2) + (dda0 - ddb0).powi(2)) + rhoDDDD).sqrt()))
        + (ev3 / ((((r0 + dda0) + ddb0).powi(2) + (dda0 + ddb0).powi(2)) + rhoDDDD).sqrt()))
        - (ev3 / ((((r0 - dda0) - ddb0).powi(2) + (dda0 - ddb0).powi(2)) + rhoDDDD).sqrt()))
        + (ev3 / ((((r0 - dda0) - ddb0).powi(2) + (dda0 + ddb0).powi(2)) + rhoDDDD).sqrt()))
        + (ev3 / ((((r0 - dda0) + ddb0).powi(2) + (dda0 - ddb0).powi(2)) + rhoDDDD).sqrt()))
        - (ev3 / ((((r0 - dda0) + ddb0).powi(2) + (dda0 + ddb0).powi(2)) + rhoDDDD).sqrt()));
    let DDQpiz_DSQpiz = ((((((((ev3
        / ((((r0 + dsb0) - dda0).powi(2) + (dsb0 - dda0).powi(2)) + rhoSDDD).sqrt())
        - (ev3 / ((((r0 + dsb0) - dda0).powi(2) + (dsb0 + dda0).powi(2)) + rhoSDDD).sqrt()))
        - (ev3 / ((((r0 + dsb0) + dda0).powi(2) + (dsb0 - dda0).powi(2)) + rhoSDDD).sqrt()))
        + (ev3 / ((((r0 + dsb0) + dda0).powi(2) + (dsb0 + dda0).powi(2)) + rhoSDDD).sqrt()))
        - (ev3 / ((((r0 - dsb0) - dda0).powi(2) + (dsb0 - dda0).powi(2)) + rhoSDDD).sqrt()))
        + (ev3 / ((((r0 - dsb0) - dda0).powi(2) + (dsb0 + dda0).powi(2)) + rhoSDDD).sqrt()))
        + (ev3 / ((((r0 - dsb0) + dda0).powi(2) + (dsb0 - dda0).powi(2)) + rhoSDDD).sqrt()))
        - (ev3 / ((((r0 - dsb0) + dda0).powi(2) + (dsb0 + dda0).powi(2)) + rhoSDDD).sqrt()));
    let DSQpiz_PPQpiz = ((((((((ev3
        / ((((r0 + qb0) - dsa0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt())
        - (ev3 / ((((r0 + qb0) - dsa0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / ((((r0 + qb0) + dsa0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt()))
        + (ev3 / ((((r0 + qb0) + dsa0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / ((((r0 - qb0) - dsa0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt()))
        + (ev3 / ((((r0 - qb0) - dsa0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        + (ev3 / ((((r0 - qb0) + dsa0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / ((((r0 - qb0) + dsa0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()));
    let DDQpiz_PPQpiz = ((((((((ev3
        / ((((r0 + qb0) - dda0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt())
        - (ev3 / ((((r0 + qb0) - dda0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / ((((r0 + qb0) + dda0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt()))
        + (ev3 / ((((r0 + qb0) + dda0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / ((((r0 - qb0) - dda0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt()))
        + (ev3 / ((((r0 - qb0) - dda0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        + (ev3 / ((((r0 - qb0) + dda0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / ((((r0 - qb0) + dda0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()));
    let dsb0 = (dsb0 * (2.0_f64).sqrt());
    let dsa0 = (dsa0 * (2.0_f64).sqrt());
    let dda0 = (dda0 * (2.0_f64).sqrt());
    let ddb0 = (ddb0 * (2.0_f64).sqrt());
    let qa0 = (qa0 * (2.0_f64).sqrt());
    let qb0 = (qb0 * (2.0_f64).sqrt());
    let PPQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt())
        + (ev2 / (((r0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (qb0).powi(2)) + rhoPPPP).sqrt()));
    let PPQxy_DSQxy = (((ev2 / (((r0).powi(2) + (qa0 - dsb0).powi(2)) + rhoSDPP).sqrt())
        + (ev2 / (((r0).powi(2) + (qa0 + dsb0).powi(2)) + rhoSDPP).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (dsb0).powi(2)) + rhoSDPP).sqrt()));
    let PPQxy_DDQxy = (((ev2 / (((r0).powi(2) + (qa0 - ddb0).powi(2)) + rhoDDPP).sqrt())
        + (ev2 / (((r0).powi(2) + (qa0 + ddb0).powi(2)) + rhoDDPP).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (ddb0).powi(2)) + rhoDDPP).sqrt()));
    let DSQxy_DSQxy = (((ev2 / (((r0).powi(2) + (dsa0 - dsb0).powi(2)) + rhoSDSD).sqrt())
        + (ev2 / (((r0).powi(2) + (dsa0 + dsb0).powi(2)) + rhoSDSD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (dsa0).powi(2)) + (dsb0).powi(2)) + rhoSDSD).sqrt()));
    let DSQxy_DDQxy = (((ev2 / (((r0).powi(2) + (dsa0 - ddb0).powi(2)) + rhoDDSD).sqrt())
        + (ev2 / (((r0).powi(2) + (dsa0 + ddb0).powi(2)) + rhoDDSD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (dsa0).powi(2)) + (ddb0).powi(2)) + rhoDDSD).sqrt()));
    let DDQxy_DDQxy = (((ev2 / (((r0).powi(2) + (dda0 - ddb0).powi(2)) + rhoDDDD).sqrt())
        + (ev2 / (((r0).powi(2) + (dda0 + ddb0).powi(2)) + rhoDDDD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (dda0).powi(2)) + (ddb0).powi(2)) + rhoDDDD).sqrt()));
    let DSQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt())
        + (ev2 / (((r0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dsa0).powi(2)) + rhoPPSD).sqrt()));
    let DDQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt())
        + (ev2 / (((r0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dda0).powi(2)) + rhoPPDD).sqrt()));
    let DDQxy_DSQxy = (((ev2 / (((r0).powi(2) + (dsb0 - dda0).powi(2)) + rhoSDDD).sqrt())
        + (ev2 / (((r0).powi(2) + (dsb0 + dda0).powi(2)) + rhoSDDD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (dsb0).powi(2)) + (dda0).powi(2)) + rhoSDDD).sqrt()));
    let qa0 = (qa0 / (2.0_f64).sqrt());
    let qb0 = (qb0 / (2.0_f64).sqrt());
    let qa0 = (qa0 * (2.0_f64).sqrt());
    let qb0 = (qb0 * (2.0_f64).sqrt());
    let tildaPPQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt())
        + (ev2 / (((r0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (qb0).powi(2)) + rhoPPPP).sqrt()));
    let tildaPPQxy_DSQxy = (((ev2 / (((r0).powi(2) + (qa0 - dsb0).powi(2)) + rhoSDPP).sqrt())
        + (ev2 / (((r0).powi(2) + (qa0 + dsb0).powi(2)) + rhoSDPP).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (dsb0).powi(2)) + rhoSDPP).sqrt()));
    let tildaPPQxy_DDQxy = (((ev2 / (((r0).powi(2) + (qa0 - ddb0).powi(2)) + rhoDDPP).sqrt())
        + (ev2 / (((r0).powi(2) + (qa0 + ddb0).powi(2)) + rhoDDPP).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (ddb0).powi(2)) + rhoDDPP).sqrt()));
    let tildaDSQxy_DSQxy = (((ev2 / (((r0).powi(2) + (dsa0 - dsb0).powi(2)) + rhoSDSD).sqrt())
        + (ev2 / (((r0).powi(2) + (dsa0 + dsb0).powi(2)) + rhoSDSD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (dsa0).powi(2)) + (dsb0).powi(2)) + rhoSDSD).sqrt()));
    let tildaDSQxy_DDQxy = (((ev2 / (((r0).powi(2) + (dsa0 - ddb0).powi(2)) + rhoDDSD).sqrt())
        + (ev2 / (((r0).powi(2) + (dsa0 + ddb0).powi(2)) + rhoDDSD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (dsa0).powi(2)) + (ddb0).powi(2)) + rhoDDSD).sqrt()));
    let tildaDDQxy_DDQxy = (((ev2 / (((r0).powi(2) + (dda0 - ddb0).powi(2)) + rhoDDDD).sqrt())
        + (ev2 / (((r0).powi(2) + (dda0 + ddb0).powi(2)) + rhoDDDD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (dda0).powi(2)) + (ddb0).powi(2)) + rhoDDDD).sqrt()));
    let tildaDSQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt())
        + (ev2 / (((r0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dsa0).powi(2)) + rhoPPSD).sqrt()));
    let tildaDDQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt())
        + (ev2 / (((r0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dda0).powi(2)) + rhoPPDD).sqrt()));
    let tildaDDQxy_DSQxy = (((ev2 / (((r0).powi(2) + (dsb0 - dda0).powi(2)) + rhoSDDD).sqrt())
        + (ev2 / (((r0).powi(2) + (dsb0 + dda0).powi(2)) + rhoSDDD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (dsb0).powi(2)) + (dda0).powi(2)) + rhoSDDD).sqrt()));
    let qa0 = (qa0 / (2.0_f64).sqrt());
    let qb0 = (qb0 / (2.0_f64).sqrt());
    output[1980] =
        (((Sq_DDq * 1.0_f64) * 1.0_f64) + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)));
    output[765] = ((Sq_DPUz * 1.0_f64) * 1.0_f64);
    output[900] =
        (((Sq_DDq * 1.0_f64) * 1.0_f64) + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64));
    output[450] = ((Sq_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64);
    output[495] = ((Sq_DPUz * 1.0_f64) * 1.154701_f64);
    output[630] =
        (((Sq_DDq * 1.0_f64) * 1.0_f64) + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64));
    output[1080] = ((Sq_DPUz * 1.0_f64) * 1.0_f64);
    output[1215] =
        (((Sq_DDq * 1.0_f64) * 1.0_f64) + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64));
    output[1575] =
        (((Sq_DDq * 1.0_f64) * 1.0_f64) + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)));
    output[1758] = ((SPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[678] = ((SPUpi_DSQpiz * 1.0_f64) * 1.0_f64);
    output[723] = ((SPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[543] = ((SPUpi_DPUpi * 1.0_f64) * (-0.57735_f64));
    output[858] = ((SPUpi_DDQpiz * 1.0_f64) * 0.57735_f64);
    output[1893] = ((SPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[1353] = ((SPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1488] = ((SPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[1985] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((PPQtzx_onehalfQtxy_DDq * (-0.666667_f64)) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-0.666667_f64)) * (-1.333333_f64)));
    output[770] =
        (((Sq_DPUz * 1.0_f64) * 1.0_f64) + ((PPQtzx_onehalfQtxy_DPUz * (-0.666667_f64)) * 1.0_f64));
    output[905] = ((((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((PPQtzx_onehalfQtxy_DDq * (-0.666667_f64)) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-0.666667_f64)) * 0.666667_f64))
        + ((PPQxy_DDQxy * 1.0_f64) * 1.0_f64));
    output[455] = (((Sq_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64)
        + ((PPQtzx_onehalfQtxy_DSQtzx_onehalfQtxy * (-0.666667_f64)) * 1.154701_f64));
    output[500] = (((Sq_DPUz * 1.0_f64) * 1.154701_f64)
        + ((PPQtzx_onehalfQtxy_DPUz * (-0.666667_f64)) * 1.154701_f64));
    output[635] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((PPQtzx_onehalfQtxy_DDq * (-0.666667_f64)) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-0.666667_f64)) * 1.333333_f64));
    output[1085] =
        (((Sq_DPUz * 1.0_f64) * 1.0_f64) + ((PPQtzx_onehalfQtxy_DPUz * (-0.666667_f64)) * 1.0_f64));
    output[1220] = ((((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((PPQtzx_onehalfQtxy_DDq * (-0.666667_f64)) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-0.666667_f64)) * 0.666667_f64))
        - ((PPQxy_DDQxy * 1.0_f64) * 1.0_f64));
    output[1265] = ((PPQxy_DSQxy * 1.0_f64) * 1.0_f64);
    output[1445] = ((PPQxy_DDQxy * 1.0_f64) * (-1.154701_f64));
    output[1580] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((PPQtzx_onehalfQtxy_DDq * (-0.666667_f64)) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-0.666667_f64)) * (-1.333333_f64)));
    output[1716] = ((SPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1851] = ((SPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[591] = (((SPUpi_DPUpi * 1.0_f64) * 1.0_f64) * (-0.57735026918963_f64));
    output[951] = ((SPUpi_DSQpiz * 1.0_f64) * 1.0_f64);
    output[996] = ((SPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1131] = (((SPUpi_DDQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1401] = (((-SPUpi_DPUpi) * 1.0_f64) * 1.0_f64);
    output[1536] = (((-SPUpi_DDQpiz) * 1.0_f64) * 1.0_f64);
    output[1628] = ((tildaPPQxy_DSQxy * 1.0_f64) * 1.0_f64);
    output[1808] = (((tildaPPQxy_DDQxy * 1.0_f64) * 1.0_f64) * (-1.1547005383793_f64));
    output[1178] = ((tildaPPQxy_DDQxy * 1.0_f64) * 1.0_f64);
    output[1989] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((PPQtzx_onehalfQtxy_DDq * (-0.666667_f64)) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-0.666667_f64)) * (-1.333333_f64)));
    output[774] =
        (((Sq_DPUz * 1.0_f64) * 1.0_f64) + ((PPQtzx_onehalfQtxy_DPUz * (-0.666667_f64)) * 1.0_f64));
    output[909] = ((((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((PPQtzx_onehalfQtxy_DDq * (-0.666667_f64)) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-0.666667_f64)) * 0.666667_f64))
        - ((PPQxy_DDQxy * 1.0_f64) * 1.0_f64));
    output[459] = (((Sq_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64)
        + ((PPQtzx_onehalfQtxy_DSQtzx_onehalfQtxy * (-0.666667_f64)) * 1.154701_f64));
    output[504] = (((Sq_DPUz * 1.0_f64) * 1.154701_f64)
        + ((PPQtzx_onehalfQtxy_DPUz * (-0.666667_f64)) * 1.154701_f64));
    output[639] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((PPQtzx_onehalfQtxy_DDq * (-0.666667_f64)) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-0.666667_f64)) * 1.333333_f64));
    output[1089] =
        (((Sq_DPUz * 1.0_f64) * 1.0_f64) + ((PPQtzx_onehalfQtxy_DPUz * (-0.666667_f64)) * 1.0_f64));
    output[1224] = ((((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((PPQtzx_onehalfQtxy_DDq * (-0.666667_f64)) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-0.666667_f64)) * 0.666667_f64))
        + ((PPQxy_DDQxy * 1.0_f64) * 1.0_f64));
    output[1269] = (((-PPQxy_DSQxy) * 1.0_f64) * 1.0_f64);
    output[1449] = (((-PPQxy_DDQxy) * 1.0_f64) * (-1.154701_f64));
    output[1584] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((PPQtzx_onehalfQtxy_DDq * (-0.666667_f64)) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-0.666667_f64)) * (-1.333333_f64)));
    output[1981] = (((SPUz_DDq * 1.0_f64) * 1.0_f64)
        + ((SPUz_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)));
    output[766] = ((SPUz_DPUz * 1.0_f64) * 1.0_f64);
    output[901] =
        (((SPUz_DDq * 1.0_f64) * 1.0_f64) + ((SPUz_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64));
    output[451] = ((SPUz_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64);
    output[496] = ((SPUz_DPUz * 1.0_f64) * 1.154701_f64);
    output[631] =
        (((SPUz_DDq * 1.0_f64) * 1.0_f64) + ((SPUz_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64));
    output[1081] = ((SPUz_DPUz * 1.0_f64) * 1.0_f64);
    output[1216] =
        (((SPUz_DDq * 1.0_f64) * 1.0_f64) + ((SPUz_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64));
    output[1576] = (((SPUz_DDq * 1.0_f64) * 1.0_f64)
        + ((SPUz_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)));
    output[1759] = ((PPQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[679] = ((PPQpiz_DSQpiz * 1.0_f64) * 1.0_f64);
    output[724] = ((PPQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[544] = ((PPQpiz_DPUpi * 1.0_f64) * (-0.57735_f64));
    output[859] = ((PPQpiz_DDQpiz * 1.0_f64) * 0.57735_f64);
    output[1894] = ((PPQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[1354] = ((PPQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1489] = ((PPQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[1717] = ((PPQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1852] = ((PPQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[592] = ((((-PPQpiz_DPUpi) * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[952] = ((PPQpiz_DSQpiz * 1.0_f64) * 1.0_f64);
    output[997] = ((PPQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1132] = (((PPQpiz_DDQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1402] = (((-PPQpiz_DPUpi) * 1.0_f64) * 1.0_f64);
    output[1537] = (((-PPQpiz_DDQpiz) * 1.0_f64) * 1.0_f64);
    output[1982] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((PPQtzx_onehalfQtxy_DDq * 1.333333_f64) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.333333_f64) * (-1.333333_f64)));
    output[767] =
        (((Sq_DPUz * 1.0_f64) * 1.0_f64) + ((PPQtzx_onehalfQtxy_DPUz * 1.333333_f64) * 1.0_f64));
    output[902] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((PPQtzx_onehalfQtxy_DDq * 1.333333_f64) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.333333_f64) * 0.666667_f64));
    output[452] = (((Sq_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64)
        + ((PPQtzx_onehalfQtxy_DSQtzx_onehalfQtxy * 1.333333_f64) * 1.154701_f64));
    output[497] = (((Sq_DPUz * 1.0_f64) * 1.154701_f64)
        + ((PPQtzx_onehalfQtxy_DPUz * 1.333333_f64) * 1.154701_f64));
    output[632] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((PPQtzx_onehalfQtxy_DDq * 1.333333_f64) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.333333_f64) * 1.333333_f64));
    output[1082] =
        (((Sq_DPUz * 1.0_f64) * 1.0_f64) + ((PPQtzx_onehalfQtxy_DPUz * 1.333333_f64) * 1.0_f64));
    output[1217] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((PPQtzx_onehalfQtxy_DDq * 1.333333_f64) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.333333_f64) * 0.666667_f64));
    output[1577] = (((((Sq_DDq * 1.0_f64) * 1.0_f64)
        + ((Sq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((PPQtzx_onehalfQtxy_DDq * 1.333333_f64) * 1.0_f64))
        + ((PPQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.333333_f64) * (-1.333333_f64)));
    output[396] = ((tildaDSQxy_PPQxy * 1.0_f64) * 1.0_f64);
    output[1656] = ((tildaDSQxy_DSQxy * 1.0_f64) * 1.0_f64);
    output[1836] = (((tildaDSQxy_DDQxy * 1.0_f64) * 1.0_f64) * (-1.1547005383793_f64));
    output[1206] = ((tildaDSQxy_DDQxy * 1.0_f64) * 1.0_f64);
    output[308] = ((DPUpi_SPUpi * 1.0_f64) * 1.0_f64);
    output[353] = ((DPUpi_PPQpiz * 1.0_f64) * 1.0_f64);
    output[1748] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1883] = ((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[623] = (((DPUpi_DPUpi * 1.0_f64) * 1.0_f64) * (-0.57735026918963_f64));
    output[983] = ((DPUpi_DSQpiz * 1.0_f64) * 1.0_f64);
    output[1028] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1163] = (((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1433] = (((-DPUpi_DPUpi) * 1.0_f64) * 1.0_f64);
    output[1568] = (((-DPUpi_DDQpiz) * 1.0_f64) * 1.0_f64);
    output[174] = ((DPUpi_SPUpi * 1.0_f64) * 1.0_f64);
    output[219] = ((DPUpi_PPQpiz * 1.0_f64) * 1.0_f64);
    output[1794] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[714] = ((DPUpi_DSQpiz * 1.0_f64) * 1.0_f64);
    output[759] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[579] = ((DPUpi_DPUpi * 1.0_f64) * (-0.57735_f64));
    output[894] = ((DPUpi_DDQpiz * 1.0_f64) * 0.57735_f64);
    output[1929] = ((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[1389] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1524] = ((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[44] =
        (((DDq_Sq * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64));
    output[269] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * (-0.666667_f64)));
    output[449] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * (-0.666667_f64)));
    output[89] = (((DDq_SPUz * 1.0_f64) * 1.0_f64)
        + ((DDQtzx_onehalfQtxy_SPUz * (-1.333333_f64)) * 1.0_f64));
    output[134] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * 1.333333_f64));
    output[2024] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((DDQtzx_onehalfQtxy_DDq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-1.333333_f64)) * (-1.333333_f64)));
    output[809] = (((DDq_DPUz * 1.0_f64) * 1.0_f64)
        + ((DDQtzx_onehalfQtxy_DPUz * (-1.333333_f64)) * 1.0_f64));
    output[944] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((DDQtzx_onehalfQtxy_DDq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-1.333333_f64)) * 0.666667_f64));
    output[494] = (((DDq_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64)
        + ((DDQtzx_onehalfQtxy_DSQtzx_onehalfQtxy * (-1.333333_f64)) * 1.154701_f64));
    output[539] = (((DDq_DPUz * 1.0_f64) * 1.154701_f64)
        + ((DDQtzx_onehalfQtxy_DPUz * (-1.333333_f64)) * 1.154701_f64));
    output[674] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_DDq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-1.333333_f64)) * 1.333333_f64));
    output[1124] = (((DDq_DPUz * 1.0_f64) * 1.0_f64)
        + ((DDQtzx_onehalfQtxy_DPUz * (-1.333333_f64)) * 1.0_f64));
    output[1259] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((DDQtzx_onehalfQtxy_DDq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-1.333333_f64)) * 0.666667_f64));
    output[1619] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((DDQtzx_onehalfQtxy_DDq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-1.333333_f64)) * (-1.333333_f64)));
    output[150] = ((DSQpiz_SPUpi * 1.0_f64) * 1.0_f64);
    output[195] = ((DSQpiz_PPQpiz * 1.0_f64) * 1.0_f64);
    output[1770] = ((DSQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[690] = ((DSQpiz_DSQpiz * 1.0_f64) * 1.0_f64);
    output[735] = ((DSQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[555] = ((DSQpiz_DPUpi * 1.0_f64) * (-0.57735_f64));
    output[870] = ((DSQpiz_DDQpiz * 1.0_f64) * 0.57735_f64);
    output[1905] = ((DSQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[1365] = ((DSQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1500] = ((DSQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[17] = ((DPUz_Sq * 1.0_f64) * 1.0_f64);
    output[242] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)));
    output[422] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)));
    output[62] = ((DPUz_SPUz * 1.0_f64) * 1.0_f64);
    output[107] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64));
    output[1997] = (((DPUz_DDq * 1.0_f64) * 1.0_f64)
        + ((DPUz_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)));
    output[782] = ((DPUz_DPUz * 1.0_f64) * 1.0_f64);
    output[917] =
        (((DPUz_DDq * 1.0_f64) * 1.0_f64) + ((DPUz_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64));
    output[467] = ((DPUz_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64);
    output[512] = ((DPUz_DPUz * 1.0_f64) * 1.154701_f64);
    output[647] =
        (((DPUz_DDq * 1.0_f64) * 1.0_f64) + ((DPUz_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64));
    output[1097] = ((DPUz_DPUz * 1.0_f64) * 1.0_f64);
    output[1232] =
        (((DPUz_DDq * 1.0_f64) * 1.0_f64) + ((DPUz_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64));
    output[1592] = (((DPUz_DDq * 1.0_f64) * 1.0_f64)
        + ((DPUz_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)));
    output[151] = ((DPUpi_SPUpi * 1.0_f64) * 1.0_f64);
    output[196] = ((DPUpi_PPQpiz * 1.0_f64) * 1.0_f64);
    output[1771] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[691] = ((DPUpi_DSQpiz * 1.0_f64) * 1.0_f64);
    output[736] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[556] = ((DPUpi_DPUpi * 1.0_f64) * (-0.57735_f64));
    output[871] = ((DPUpi_DDQpiz * 1.0_f64) * 0.57735_f64);
    output[1906] = ((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[1366] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1501] = ((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[311] = ((DDQpiz_SPUpi * 1.0_f64) * 1.0_f64);
    output[356] = ((DDQpiz_PPQpiz * 1.0_f64) * 1.0_f64);
    output[1751] = ((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1886] = ((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[626] = (((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64) * (-0.57735026918963_f64));
    output[986] = ((DDQpiz_DSQpiz * 1.0_f64) * 1.0_f64);
    output[1031] = ((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1166] = (((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1436] = (((-DDQpiz_DPUpi) * 1.0_f64) * 1.0_f64);
    output[1571] = (((-DDQpiz_DDQpiz) * 1.0_f64) * 1.0_f64);
    output[20] =
        (((DDq_Sq * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64));
    output[245] = ((((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * (-0.666667_f64)))
        + ((DDQxy_PPQxy * 1.0_f64) * 1.0_f64));
    output[425] = ((((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * (-0.666667_f64)))
        - ((DDQxy_PPQxy * 1.0_f64) * 1.0_f64));
    output[65] =
        (((DDq_SPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_SPUz * 0.666667_f64) * 1.0_f64));
    output[110] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * 1.333333_f64));
    output[2000] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((DDQtzx_onehalfQtxy_DDq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 0.666667_f64) * (-1.333333_f64)));
    output[785] =
        (((DDq_DPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_DPUz * 0.666667_f64) * 1.0_f64));
    output[920] = ((((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((DDQtzx_onehalfQtxy_DDq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 0.666667_f64) * 0.666667_f64))
        + ((DDQxy_DDQxy * 1.0_f64) * 1.0_f64));
    output[470] = (((DDq_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64)
        + ((DDQtzx_onehalfQtxy_DSQtzx_onehalfQtxy * 0.666667_f64) * 1.154701_f64));
    output[515] = (((DDq_DPUz * 1.0_f64) * 1.154701_f64)
        + ((DDQtzx_onehalfQtxy_DPUz * 0.666667_f64) * 1.154701_f64));
    output[650] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_DDq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 0.666667_f64) * 1.333333_f64));
    output[1100] =
        (((DDq_DPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_DPUz * 0.666667_f64) * 1.0_f64));
    output[1235] = ((((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((DDQtzx_onehalfQtxy_DDq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 0.666667_f64) * 0.666667_f64))
        - ((DDQxy_DDQxy * 1.0_f64) * 1.0_f64));
    output[1280] = ((DDQxy_DSQxy * 1.0_f64) * 1.0_f64);
    output[1460] = ((DDQxy_DDQxy * 1.0_f64) * (-1.154701_f64));
    output[1595] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((DDQtzx_onehalfQtxy_DDq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 0.666667_f64) * (-1.333333_f64)));
    output[10] = ((DSQtzx_onehalfQtxy_Sq * 1.154701_f64) * 1.0_f64);
    output[235] = (((DSQtzx_onehalfQtxy_Sq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.154701_f64) * (-0.666667_f64)));
    output[415] = (((DSQtzx_onehalfQtxy_Sq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.154701_f64) * (-0.666667_f64)));
    output[55] = ((DSQtzx_onehalfQtxy_SPUz * 1.154701_f64) * 1.0_f64);
    output[100] = (((DSQtzx_onehalfQtxy_Sq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.154701_f64) * 1.333333_f64));
    output[1990] = (((DSQtzx_onehalfQtxy_DDq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.154701_f64) * (-1.333333_f64)));
    output[775] = ((DSQtzx_onehalfQtxy_DPUz * 1.154701_f64) * 1.0_f64);
    output[910] = (((DSQtzx_onehalfQtxy_DDq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.154701_f64) * 0.666667_f64));
    output[460] = ((DSQtzx_onehalfQtxy_DSQtzx_onehalfQtxy * 1.154701_f64) * 1.154701_f64);
    output[505] = ((DSQtzx_onehalfQtxy_DPUz * 1.154701_f64) * 1.154701_f64);
    output[640] = (((DSQtzx_onehalfQtxy_DDq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.154701_f64) * 1.333333_f64));
    output[1090] = ((DSQtzx_onehalfQtxy_DPUz * 1.154701_f64) * 1.0_f64);
    output[1225] = (((DSQtzx_onehalfQtxy_DDq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.154701_f64) * 0.666667_f64));
    output[1585] = (((DSQtzx_onehalfQtxy_DDq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.154701_f64) * (-1.333333_f64)));
    output[147] = ((DPUpi_SPUpi * (-0.57735_f64)) * 1.0_f64);
    output[192] = ((DPUpi_PPQpiz * (-0.57735_f64)) * 1.0_f64);
    output[1767] = ((DPUpi_DPUpi * (-0.57735_f64)) * 1.0_f64);
    output[687] = ((DPUpi_DSQpiz * (-0.57735_f64)) * 1.0_f64);
    output[732] = ((DPUpi_DPUpi * (-0.57735_f64)) * 1.0_f64);
    output[552] = ((DPUpi_DPUpi * (-0.57735_f64)) * (-0.57735_f64));
    output[867] = ((DPUpi_DDQpiz * (-0.57735_f64)) * 0.57735_f64);
    output[1902] = ((DPUpi_DDQpiz * (-0.57735_f64)) * 1.0_f64);
    output[1362] = ((DPUpi_DPUpi * (-0.57735_f64)) * 1.0_f64);
    output[1497] = ((DPUpi_DDQpiz * (-0.57735_f64)) * 1.0_f64);
    output[283] = (((DPUpi_SPUpi * 1.0_f64) * 1.0_f64) * (-0.57735_f64));
    output[328] = ((((-DPUpi_PPQpiz) * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1723] = (((DPUpi_DPUpi * 1.0_f64) * 1.0_f64) * (-0.57735026918963_f64));
    output[1858] = (((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64) * (-0.57735026918963_f64));
    output[598] = ((DPUpi_DPUpi * 0.57735026918963_f64) * 0.57735026918963_f64);
    output[958] = (((DPUpi_DSQpiz * 1.0_f64) * 1.0_f64) * (-0.57735026918963_f64));
    output[1003] = (((DPUpi_DPUpi * 1.0_f64) * 1.0_f64) * (-0.57735026918963_f64));
    output[1138] =
        ((((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64) * (-0.57735026918963_f64));
    output[1408] = (((DPUpi_DPUpi * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1543] = (((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[11] = ((DPUz_Sq * 1.154701_f64) * 1.0_f64);
    output[236] = (((DPUz_Sq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_PPQtzx_onehalfQtxy * 1.154701_f64) * (-0.666667_f64)));
    output[416] = (((DPUz_Sq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_PPQtzx_onehalfQtxy * 1.154701_f64) * (-0.666667_f64)));
    output[56] = ((DPUz_SPUz * 1.154701_f64) * 1.0_f64);
    output[101] = (((DPUz_Sq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_PPQtzx_onehalfQtxy * 1.154701_f64) * 1.333333_f64));
    output[1991] = (((DPUz_DDq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_DDQtzx_onehalfQtxy * 1.154701_f64) * (-1.333333_f64)));
    output[776] = ((DPUz_DPUz * 1.154701_f64) * 1.0_f64);
    output[911] = (((DPUz_DDq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_DDQtzx_onehalfQtxy * 1.154701_f64) * 0.666667_f64));
    output[461] = ((DPUz_DSQtzx_onehalfQtxy * 1.154701_f64) * 1.154701_f64);
    output[506] = ((DPUz_DPUz * 1.154701_f64) * 1.154701_f64);
    output[641] = (((DPUz_DDq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_DDQtzx_onehalfQtxy * 1.154701_f64) * 1.333333_f64));
    output[1091] = ((DPUz_DPUz * 1.154701_f64) * 1.0_f64);
    output[1226] = (((DPUz_DDq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_DDQtzx_onehalfQtxy * 1.154701_f64) * 0.666667_f64));
    output[1586] = (((DPUz_DDq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_DDQtzx_onehalfQtxy * 1.154701_f64) * (-1.333333_f64)));
    output[400] = (((tildaDDQxy_PPQxy * 1.0_f64) * 1.0_f64) * (-1.1547005383793_f64));
    output[1660] = (((tildaDDQxy_DSQxy * 1.0_f64) * 1.0_f64) * (-1.1547005383793_f64));
    output[1840] = (((tildaDDQxy_DDQxy * 1.0_f64) * 1.0_f64) * 1.333333333333333_f64);
    output[1210] = (((tildaDDQxy_DDQxy * 1.0_f64) * 1.0_f64) * (-1.1547005383793_f64));
    output[154] = ((DDQpiz_SPUpi * 0.57735_f64) * 1.0_f64);
    output[199] = ((DDQpiz_PPQpiz * 0.57735_f64) * 1.0_f64);
    output[1774] = ((DDQpiz_DPUpi * 0.57735_f64) * 1.0_f64);
    output[694] = ((DDQpiz_DSQpiz * 0.57735_f64) * 1.0_f64);
    output[739] = ((DDQpiz_DPUpi * 0.57735_f64) * 1.0_f64);
    output[559] = ((DDQpiz_DPUpi * 0.57735_f64) * (-0.57735_f64));
    output[874] = ((DDQpiz_DDQpiz * 0.57735_f64) * 0.57735_f64);
    output[1909] = ((DDQpiz_DDQpiz * 0.57735_f64) * 1.0_f64);
    output[1369] = ((DDQpiz_DPUpi * 0.57735_f64) * 1.0_f64);
    output[1504] = ((DDQpiz_DDQpiz * 0.57735_f64) * 1.0_f64);
    output[14] =
        (((DDq_Sq * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_Sq * 1.333333_f64) * 1.0_f64));
    output[239] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.333333_f64) * (-0.666667_f64)));
    output[419] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.333333_f64) * (-0.666667_f64)));
    output[59] =
        (((DDq_SPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_SPUz * 1.333333_f64) * 1.0_f64));
    output[104] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_Sq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.333333_f64) * 1.333333_f64));
    output[1994] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((DDQtzx_onehalfQtxy_DDq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.333333_f64) * (-1.333333_f64)));
    output[779] =
        (((DDq_DPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_DPUz * 1.333333_f64) * 1.0_f64));
    output[914] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((DDQtzx_onehalfQtxy_DDq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.333333_f64) * 0.666667_f64));
    output[464] = (((DDq_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64)
        + ((DDQtzx_onehalfQtxy_DSQtzx_onehalfQtxy * 1.333333_f64) * 1.154701_f64));
    output[509] = (((DDq_DPUz * 1.0_f64) * 1.154701_f64)
        + ((DDQtzx_onehalfQtxy_DPUz * 1.333333_f64) * 1.154701_f64));
    output[644] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_DDq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.333333_f64) * 1.333333_f64));
    output[1094] =
        (((DDq_DPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_DPUz * 1.333333_f64) * 1.0_f64));
    output[1229] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((DDQtzx_onehalfQtxy_DDq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.333333_f64) * 0.666667_f64));
    output[1589] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((DDQtzx_onehalfQtxy_DDq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 1.333333_f64) * (-1.333333_f64)));
    output[291] = ((DSQpiz_SPUpi * 1.0_f64) * 1.0_f64);
    output[336] = ((DSQpiz_PPQpiz * 1.0_f64) * 1.0_f64);
    output[1731] = ((DSQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1866] = ((DSQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[606] = (((DSQpiz_DPUpi * 1.0_f64) * 1.0_f64) * (-0.57735026918963_f64));
    output[966] = ((DSQpiz_DSQpiz * 1.0_f64) * 1.0_f64);
    output[1011] = ((DSQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1146] = (((DSQpiz_DDQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1416] = (((-DSQpiz_DPUpi) * 1.0_f64) * 1.0_f64);
    output[1551] = (((-DSQpiz_DDQpiz) * 1.0_f64) * 1.0_f64);
    output[24] = ((DPUz_Sq * 1.0_f64) * 1.0_f64);
    output[249] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)));
    output[429] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)));
    output[69] = ((DPUz_SPUz * 1.0_f64) * 1.0_f64);
    output[114] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64));
    output[2004] = (((DPUz_DDq * 1.0_f64) * 1.0_f64)
        + ((DPUz_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)));
    output[789] = ((DPUz_DPUz * 1.0_f64) * 1.0_f64);
    output[924] =
        (((DPUz_DDq * 1.0_f64) * 1.0_f64) + ((DPUz_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64));
    output[474] = ((DPUz_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64);
    output[519] = ((DPUz_DPUz * 1.0_f64) * 1.154701_f64);
    output[654] =
        (((DPUz_DDq * 1.0_f64) * 1.0_f64) + ((DPUz_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64));
    output[1104] = ((DPUz_DPUz * 1.0_f64) * 1.0_f64);
    output[1239] =
        (((DPUz_DDq * 1.0_f64) * 1.0_f64) + ((DPUz_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64));
    output[1599] = (((DPUz_DDq * 1.0_f64) * 1.0_f64)
        + ((DPUz_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)));
    output[292] = ((DPUpi_SPUpi * 1.0_f64) * 1.0_f64);
    output[337] = ((DPUpi_PPQpiz * 1.0_f64) * 1.0_f64);
    output[1732] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1867] = ((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[607] = (((DPUpi_DPUpi * 1.0_f64) * 1.0_f64) * (-0.57735026918963_f64));
    output[967] = ((DPUpi_DSQpiz * 1.0_f64) * 1.0_f64);
    output[1012] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1147] = (((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1417] = (((-DPUpi_DPUpi) * 1.0_f64) * 1.0_f64);
    output[1552] = (((-DPUpi_DDQpiz) * 1.0_f64) * 1.0_f64);
    output[177] = ((DDQpiz_SPUpi * 1.0_f64) * 1.0_f64);
    output[222] = ((DDQpiz_PPQpiz * 1.0_f64) * 1.0_f64);
    output[1797] = ((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[717] = ((DDQpiz_DSQpiz * 1.0_f64) * 1.0_f64);
    output[762] = ((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[582] = ((DDQpiz_DPUpi * 1.0_f64) * (-0.57735_f64));
    output[897] = ((DDQpiz_DDQpiz * 1.0_f64) * 0.57735_f64);
    output[1932] = ((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[1392] = ((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1527] = ((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[386] = ((tildaDDQxy_PPQxy * 1.0_f64) * 1.0_f64);
    output[1646] = ((DDQxy_DSQxy * 1.0_f64) * 1.0_f64);
    output[1826] = (((tildaDDQxy_DDQxy * 1.0_f64) * 1.0_f64) * (-1.1547005383793_f64));
    output[1196] = ((tildaDDQxy_DDQxy * 1.0_f64) * 1.0_f64);
    output[295] = (((DDQpiz_SPUpi * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[340] = (((DDQpiz_PPQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1735] = (((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1870] = (((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[610] =
        ((((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64) * (-0.57735026918963_f64));
    output[970] = (((DDQpiz_DSQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1015] = (((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[1150] =
        ((((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64) * 0.5773502691896295_f64);
    output[1420] = (((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64) * (-0.5773502691896295_f64));
    output[1555] = (((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64) * (-0.5773502691896295_f64));
    output[27] =
        (((DDq_Sq * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64));
    output[252] = ((((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * (-0.666667_f64)))
        - ((DDQxy_PPQxy * 1.0_f64) * 1.0_f64));
    output[432] = ((((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * (-0.666667_f64)))
        + ((DDQxy_PPQxy * 1.0_f64) * 1.0_f64));
    output[72] =
        (((DDq_SPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_SPUz * 0.666667_f64) * 1.0_f64));
    output[117] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * 1.333333_f64));
    output[2007] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((DDQtzx_onehalfQtxy_DDq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 0.666667_f64) * (-1.333333_f64)));
    output[792] =
        (((DDq_DPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_DPUz * 0.666667_f64) * 1.0_f64));
    output[927] = ((((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((DDQtzx_onehalfQtxy_DDq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 0.666667_f64) * 0.666667_f64))
        - ((DDQxy_DDQxy * 1.0_f64) * 1.0_f64));
    output[477] = (((DDq_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64)
        + ((DDQtzx_onehalfQtxy_DSQtzx_onehalfQtxy * 0.666667_f64) * 1.154701_f64));
    output[522] = (((DDq_DPUz * 1.0_f64) * 1.154701_f64)
        + ((DDQtzx_onehalfQtxy_DPUz * 0.666667_f64) * 1.154701_f64));
    output[657] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_DDq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 0.666667_f64) * 1.333333_f64));
    output[1107] =
        (((DDq_DPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_DPUz * 0.666667_f64) * 1.0_f64));
    output[1242] = ((((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((DDQtzx_onehalfQtxy_DDq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 0.666667_f64) * 0.666667_f64))
        + ((DDQxy_DDQxy * 1.0_f64) * 1.0_f64));
    output[1287] = (((-DDQxy_DSQxy) * 1.0_f64) * 1.0_f64);
    output[1467] = (((-DDQxy_DDQxy) * 1.0_f64) * (-1.154701_f64));
    output[1602] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((DDQtzx_onehalfQtxy_DDq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * 0.666667_f64) * (-1.333333_f64)));
    output[253] = ((DSQxy_PPQxy * 1.0_f64) * 1.0_f64);
    output[433] = (((-DSQxy_PPQxy) * 1.0_f64) * 1.0_f64);
    output[928] = ((DSQxy_DDQxy * 1.0_f64) * 1.0_f64);
    output[1243] = (((-DSQxy_DDQxy) * 1.0_f64) * 1.0_f64);
    output[1288] = ((DSQxy_DSQxy * 1.0_f64) * 1.0_f64);
    output[1468] = ((DSQxy_DDQxy * 1.0_f64) * (-1.154701_f64));
    output[165] = ((DPUpi_SPUpi * 1.0_f64) * 1.0_f64);
    output[210] = ((DPUpi_PPQpiz * 1.0_f64) * 1.0_f64);
    output[1785] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[705] = ((DPUpi_DSQpiz * 1.0_f64) * 1.0_f64);
    output[750] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[570] = ((DPUpi_DPUpi * 1.0_f64) * (-0.57735_f64));
    output[885] = ((DPUpi_DDQpiz * 1.0_f64) * 0.57735_f64);
    output[1920] = ((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[1380] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1515] = ((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[301] = (((-DPUpi_SPUpi) * 1.0_f64) * 1.0_f64);
    output[346] = (((-DPUpi_PPQpiz) * 1.0_f64) * 1.0_f64);
    output[1741] = (((-DPUpi_DPUpi) * 1.0_f64) * 1.0_f64);
    output[1876] = (((-DPUpi_DDQpiz) * 1.0_f64) * 1.0_f64);
    output[616] = (((DPUpi_DPUpi * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[976] = (((-DPUpi_DSQpiz) * 1.0_f64) * 1.0_f64);
    output[1021] = (((-DPUpi_DPUpi) * 1.0_f64) * 1.0_f64);
    output[1156] = (((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64) * (-0.5773502691896295_f64));
    output[1426] = ((DPUpi_DPUpi * 1.0_f64) * 1.0_f64);
    output[1561] = ((DPUpi_DDQpiz * 1.0_f64) * 1.0_f64);
    output[168] = ((DDQpiz_SPUpi * 1.0_f64) * 1.0_f64);
    output[213] = ((DDQpiz_PPQpiz * 1.0_f64) * 1.0_f64);
    output[1788] = ((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[708] = ((DDQpiz_DSQpiz * 1.0_f64) * 1.0_f64);
    output[753] = ((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[573] = ((DDQpiz_DPUpi * 1.0_f64) * (-0.57735_f64));
    output[888] = ((DDQpiz_DDQpiz * 1.0_f64) * 0.57735_f64);
    output[1923] = ((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[1383] = ((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1518] = ((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[257] = ((DDQxy_PPQxy * (-1.154701_f64)) * 1.0_f64);
    output[437] = (((-DDQxy_PPQxy) * (-1.154701_f64)) * 1.0_f64);
    output[932] = ((DDQxy_DDQxy * (-1.154701_f64)) * 1.0_f64);
    output[1247] = (((-DDQxy_DDQxy) * (-1.154701_f64)) * 1.0_f64);
    output[1292] = ((DDQxy_DSQxy * (-1.154701_f64)) * 1.0_f64);
    output[1472] = ((DDQxy_DDQxy * (-1.154701_f64)) * (-1.154701_f64));
    output[304] = (((-DDQpiz_SPUpi) * 1.0_f64) * 1.0_f64);
    output[349] = (((-DDQpiz_PPQpiz) * 1.0_f64) * 1.0_f64);
    output[1744] = (((-DDQpiz_DPUpi) * 1.0_f64) * 1.0_f64);
    output[1879] = (((-DDQpiz_DDQpiz) * 1.0_f64) * 1.0_f64);
    output[619] = (((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[979] = (((-DDQpiz_DSQpiz) * 1.0_f64) * 1.0_f64);
    output[1024] = (((-DDQpiz_DPUpi) * 1.0_f64) * 1.0_f64);
    output[1159] = (((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64) * (-0.5773502691896295_f64));
    output[1429] = ((DDQpiz_DPUpi * 1.0_f64) * 1.0_f64);
    output[1564] = ((DDQpiz_DDQpiz * 1.0_f64) * 1.0_f64);
    output[35] =
        (((DDq_Sq * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64));
    output[260] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * (-0.666667_f64)));
    output[440] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * (-0.666667_f64)));
    output[80] = (((DDq_SPUz * 1.0_f64) * 1.0_f64)
        + ((DDQtzx_onehalfQtxy_SPUz * (-1.333333_f64)) * 1.0_f64));
    output[125] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * 1.333333_f64));
    output[2015] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((DDQtzx_onehalfQtxy_DDq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-1.333333_f64)) * (-1.333333_f64)));
    output[800] = (((DDq_DPUz * 1.0_f64) * 1.0_f64)
        + ((DDQtzx_onehalfQtxy_DPUz * (-1.333333_f64)) * 1.0_f64));
    output[935] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((DDQtzx_onehalfQtxy_DDq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-1.333333_f64)) * 0.666667_f64));
    output[485] = (((DDq_DSQtzx_onehalfQtxy * 1.0_f64) * 1.154701_f64)
        + ((DDQtzx_onehalfQtxy_DSQtzx_onehalfQtxy * (-1.333333_f64)) * 1.154701_f64));
    output[530] = (((DDq_DPUz * 1.0_f64) * 1.154701_f64)
        + ((DDQtzx_onehalfQtxy_DPUz * (-1.333333_f64)) * 1.154701_f64));
    output[665] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_DDq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-1.333333_f64)) * 1.333333_f64));
    output[1115] = (((DDq_DPUz * 1.0_f64) * 1.0_f64)
        + ((DDQtzx_onehalfQtxy_DPUz * (-1.333333_f64)) * 1.0_f64));
    output[1250] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * 0.666667_f64))
        + ((DDQtzx_onehalfQtxy_DDq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-1.333333_f64)) * 0.666667_f64));
    output[1610] = (((((DDq_DDq * 1.0_f64) * 1.0_f64)
        + ((DDq_DDQtzx_onehalfQtxy * 1.0_f64) * (-1.333333_f64)))
        + ((DDQtzx_onehalfQtxy_DDq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_DDQtzx_onehalfQtxy * (-1.333333_f64)) * (-1.333333_f64)));
    output
}
