// @generated by compute/semiempirical/generate-pm6-two-center.py; do not edit.
// Source: PYSEQM two_elec_two_center_int_local_frame_d_orbitals.py
// SHA-256: aca9f065544fb9aacddf15ace0c0cb03d887481b9fa45f71835b49c95b3b17af

#[derive(Clone, Copy, Debug)]
pub(super) struct Pm6YxLocalInput {
    pub r0: f64,
    pub da0: f64,
    pub db0: f64,
    pub qa0: f64,
    pub qb0: f64,
    pub dpa0: f64,
    pub dsa0: f64,
    pub dda0: f64,
    pub rho0a: f64,
    pub rho0b: f64,
    pub rho1a: f64,
    pub rho1b: f64,
    pub rho2a: f64,
    pub rho2b: f64,
    pub rho3a: f64,
    pub rho4a: f64,
    pub rho5a: f64,
    pub rho6a: f64,
}

#[allow(non_snake_case, unused_variables, unused_parens)]
pub(super) fn pm6_yx_local(input: Pm6YxLocalInput) -> [f64; 450] {
    let (ev, ev1, ev2, ev3, ev4) = (
        27.21_f64,
        27.21 / 2.0,
        27.21 / 4.0,
        27.21 / 8.0,
        27.21 / 16.0,
    );
    let mut output = [0.0; 450];
    let r0 = input.r0;
    let da0 = input.da0;
    let db0 = input.db0;
    let qa0 = input.qa0;
    let qb0 = input.qb0;
    let dpa0 = input.dpa0;
    let dsa0 = input.dsa0;
    let dda0 = input.dda0;
    let rho0a = input.rho0a;
    let rho0b = input.rho0b;
    let rho1a = input.rho1a;
    let rho1b = input.rho1b;
    let rho2a = input.rho2a;
    let rho2b = input.rho2b;
    let rho3a = input.rho3a;
    let rho4a = input.rho4a;
    let rho5a = input.rho5a;
    let rho6a = input.rho6a;
    let rhoSS = (rho0a + rho0b).powi(2);
    let rhoSDD0 = (rho3a + rho0b).powi(2);
    let rhoSSP = (rho1a + rho0b).powi(2);
    let rhoSPD = (rho4a + rho0b).powi(2);
    let rhoSPP = (rho2a + rho0b).powi(2);
    let rhoSSD = (rho5a + rho0b).powi(2);
    let rhoSDD = (rho6a + rho0b).powi(2);
    let rhoDD0SP = (rho3a + rho1b).powi(2);
    let rhoDD0PP = (rho3a + rho2b).powi(2);
    let rhoSPSP = (rho1a + rho1b).powi(2);
    let rhoSPPD = (rho4a + rho1b).powi(2);
    let rhoSPPP = (rho2a + rho1b).powi(2);
    let rhoSPSD = (rho5a + rho1b).powi(2);
    let rhoSPDD = (rho6a + rho1b).powi(2);
    let rhoPDPP = (rho4a + rho2b).powi(2);
    let rhoPPPP = (rho2a + rho2b).powi(2);
    let rhoPPDD = (rho6a + rho2b).powi(2);
    let rhoPPSD = (rho5a + rho2b).powi(2);
    let qq = (ev / ((r0).powi(2) + rhoSS).sqrt());
    let DDq_Sq = (ev / ((r0).powi(2) + rhoSDD0).sqrt());
    let Sq_SPUz = (-((ev1 / ((r0 + db0).powi(2) + rhoSSP).sqrt())
        - (ev1 / ((r0 - db0).powi(2) + rhoSSP).sqrt())));
    let DDq_SPUz = (-((ev1 / ((r0 + db0).powi(2) + rhoDD0SP).sqrt())
        - (ev1 / ((r0 - db0).powi(2) + rhoDD0SP).sqrt())));
    let DPUz_Sq = ((ev1 / ((r0 + dpa0).powi(2) + rhoSPD).sqrt())
        - (ev1 / ((r0 - dpa0).powi(2) + rhoSPD).sqrt()));
    let SPUz_Sq = ((ev1 / ((r0 + da0).powi(2) + rhoSSP).sqrt())
        - (ev1 / ((r0 - da0).powi(2) + rhoSSP).sqrt()));
    let qb0 = (qb0 * (2.0_f64).sqrt());
    let Sq_PPQtzx_onehalfQtxy = (((ev2 / ((r0 - (2.0_f64 * qb0)).powi(2) + rhoSPP).sqrt())
        + (ev2 / ((r0 + (2.0_f64 * qb0)).powi(2) + rhoSPP).sqrt()))
        - (ev1 / (((r0).powi(2) + (0.0_f64 * db0).powi(2)) + rhoSPP).sqrt()));
    let DDq_PPQtzx_onehalfQtxy = (((ev2 / ((r0 - qb0).powi(2) + rhoDD0PP).sqrt())
        + (ev2 / ((r0 + qb0).powi(2) + rhoDD0PP).sqrt()))
        - (ev1 / (((r0).powi(2) + (qb0).powi(2)) + rhoDD0PP).sqrt()));
    let DDQtzx_onehalfQtxy_Sq = (((ev2 / ((r0 - dda0).powi(2) + rhoSDD).sqrt())
        + (ev2 / ((r0 + dda0).powi(2) + rhoSDD).sqrt()))
        - (ev1 / (((r0).powi(2) + (dda0).powi(2)) + rhoSDD).sqrt()));
    let DSQtzx_onehalfQtxy_Sq = (((ev2 / ((r0 - dsa0).powi(2) + rhoSSD).sqrt())
        + (ev2 / ((r0 + dsa0).powi(2) + rhoSSD).sqrt()))
        - (ev1 / (((r0).powi(2) + (dsa0).powi(2)) + rhoSSD).sqrt()));
    let PPQtzx_onehalfQtxy_Sq = (((ev2 / ((r0 - qa0).powi(2) + rhoSPP).sqrt())
        + (ev2 / ((r0 + qa0).powi(2) + rhoSPP).sqrt()))
        - (ev1 / (((r0).powi(2) + (da0).powi(2)) + rhoSPP).sqrt()));
    let qb0 = (qb0 / (2.0_f64).sqrt());
    let SPUpi_SPUpi = ((ev1 / (((r0).powi(2) + (da0 - qb0).powi(2)) + rhoSPSP).sqrt())
        - (ev1 / (((r0).powi(2) + (da0 + qb0).powi(2)) + rhoSPSP).sqrt()));
    let DPUpi_SPUpi = ((ev1 / (((r0).powi(2) + (db0 - dpa0).powi(2)) + rhoSPPD).sqrt())
        - (ev1 / (((r0).powi(2) + (db0 + dpa0).powi(2)) + rhoSPPD).sqrt()));
    let SPUz_SPUz = ((((ev2 / (((r0 + da0) - db0).powi(2) + rhoSPSP).sqrt())
        - (ev2 / (((r0 + da0) + db0).powi(2) + rhoSPSP).sqrt()))
        - (ev2 / (((r0 - da0) - db0).powi(2) + rhoSPSP).sqrt()))
        + (ev2 / (((r0 - da0) + db0).powi(2) + rhoSPSP).sqrt()));
    let DPUz_SPUz = ((((ev2 / (((r0 + db0) - dpa0).powi(2) + rhoSPPD).sqrt())
        - (ev2 / (((r0 + db0) + dpa0).powi(2) + rhoSPPD).sqrt()))
        - (ev2 / (((r0 - db0) - dpa0).powi(2) + rhoSPPD).sqrt()))
        + (ev2 / (((r0 - db0) + dpa0).powi(2) + rhoSPPD).sqrt()));
    let dsa0 = (dsa0 / (2.0_f64).sqrt());
    let dda0 = (dda0 / (2.0_f64).sqrt());
    let SPUpi_PPQpiz = (-(((((-ev2)
        / (((r0 - qb0).powi(2) + (da0 - qb0).powi(2)) + rhoSPPP).sqrt())
        + (ev2 / (((r0 - qb0).powi(2) + (da0 + qb0).powi(2)) + rhoSPPP).sqrt()))
        + (ev2 / (((r0 + qb0).powi(2) + (da0 - qb0).powi(2)) + rhoSPPP).sqrt()))
        - (ev2 / (((r0 + qb0).powi(2) + (da0 + qb0).powi(2)) + rhoSPPP).sqrt())));
    let DPUpi_PPQpiz = (-(((((-ev2)
        / (((r0 - qb0).powi(2) + (dpa0 - qb0).powi(2)) + rhoPDPP).sqrt())
        + (ev2 / (((r0 - qb0).powi(2) + (dpa0 + qb0).powi(2)) + rhoPDPP).sqrt()))
        + (ev2 / (((r0 + qb0).powi(2) + (dpa0 - qb0).powi(2)) + rhoPDPP).sqrt()))
        - (ev2 / (((r0 + qb0).powi(2) + (dpa0 + qb0).powi(2)) + rhoPDPP).sqrt())));
    let PPQpiz_SPUpi = (((((-ev2)
        / (((r0 - qa0).powi(2) + (db0 - qa0).powi(2)) + rhoSPPP).sqrt())
        + (ev2 / (((r0 - qa0).powi(2) + (db0 + qa0).powi(2)) + rhoSPPP).sqrt()))
        + (ev2 / (((r0 + qa0).powi(2) + (db0 - qa0).powi(2)) + rhoSPPP).sqrt()))
        - (ev2 / (((r0 + qa0).powi(2) + (db0 + qa0).powi(2)) + rhoSPPP).sqrt()));
    let DSQpiz_SPUpi = (((((-ev2)
        / (((r0 - dsa0).powi(2) + (db0 - dsa0).powi(2)) + rhoSPSD).sqrt())
        + (ev2 / (((r0 - dsa0).powi(2) + (db0 + dsa0).powi(2)) + rhoSPSD).sqrt()))
        + (ev2 / (((r0 + dsa0).powi(2) + (db0 - dsa0).powi(2)) + rhoSPSD).sqrt()))
        - (ev2 / (((r0 + dsa0).powi(2) + (db0 + dsa0).powi(2)) + rhoSPSD).sqrt()));
    let DDQpiz_SPUpi = (((((-ev2)
        / (((r0 - dda0).powi(2) + (db0 - dda0).powi(2)) + rhoSPDD).sqrt())
        + (ev2 / (((r0 - dda0).powi(2) + (db0 + dda0).powi(2)) + rhoSPDD).sqrt()))
        + (ev2 / (((r0 + dda0).powi(2) + (db0 - dda0).powi(2)) + rhoSPDD).sqrt()))
        - (ev2 / (((r0 + dda0).powi(2) + (db0 + dda0).powi(2)) + rhoSPDD).sqrt()));
    let dsa0 = (dsa0 * (2.0_f64).sqrt());
    let dda0 = (dda0 * (2.0_f64).sqrt());
    let qa0 = (qa0 * (2.0_f64).sqrt());
    let qb0 = (qb0 * (2.0_f64).sqrt());
    let SPUz_PPQtzx_onehalfQtxy = (((((((-ev3)
        / (((r0 - da0) - ((1.0_f64).sqrt() * qb0)).powi(2) + rhoSPPP).sqrt())
        - (ev3 / (((r0 - da0) + ((1.0_f64).sqrt() * qb0)).powi(2) + rhoSPPP).sqrt()))
        + (ev3 / (((r0 + da0) - ((1.0_f64).sqrt() * qb0)).powi(2) + rhoSPPP).sqrt()))
        + (ev3 / (((r0 + da0) + ((1.0_f64).sqrt() * qb0)).powi(2) + rhoSPPP).sqrt()))
        + (ev2 / (((r0 - da0).powi(2) + ((1.0_f64).sqrt() * qb0).powi(2)) + rhoSPPP).sqrt()))
        - (ev2 / (((r0 + da0).powi(2) + ((1.0_f64).sqrt() * qb0).powi(2)) + rhoSPPP).sqrt()));
    let DPUz_PPQtzx_onehalfQtxy = (((((((-ev3)
        / (((r0 - dpa0) - ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPDPP).sqrt())
        - (ev3 / (((r0 - dpa0) + ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPDPP).sqrt()))
        + (ev3 / (((r0 + dpa0) - ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPDPP).sqrt()))
        + (ev3 / (((r0 + dpa0) + ((1.0_f64).sqrt() * qb0)).powi(2) + rhoPDPP).sqrt()))
        + (ev2 / (((r0 - dpa0).powi(2) + ((1.0_f64).sqrt() * qb0).powi(2)) + rhoPDPP).sqrt()))
        - (ev2 / (((r0 + dpa0).powi(2) + ((1.0_f64).sqrt() * qb0).powi(2)) + rhoPDPP).sqrt()));
    let PPQtzx_onehalfQtxy_SPUz = (-(((((((-ev3)
        / (((r0 - db0) - ((1.0_f64).sqrt() * qa0)).powi(2) + rhoSPPP).sqrt())
        - (ev3 / (((r0 - db0) + ((1.0_f64).sqrt() * qa0)).powi(2) + rhoSPPP).sqrt()))
        + (ev3 / (((r0 + db0) - ((1.0_f64).sqrt() * qa0)).powi(2) + rhoSPPP).sqrt()))
        + (ev3 / (((r0 + db0) + ((1.0_f64).sqrt() * qa0)).powi(2) + rhoSPPP).sqrt()))
        + (ev2 / (((r0 - db0).powi(2) + ((1.0_f64).sqrt() * qa0).powi(2)) + rhoSPPP).sqrt()))
        - (ev2 / (((r0 + db0).powi(2) + ((1.0_f64).sqrt() * qa0).powi(2)) + rhoSPPP).sqrt())));
    let DSQtzx_onehalfQtxy_SPUz = (-(((((((-ev3)
        / (((r0 - db0) - ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoSPSD).sqrt())
        - (ev3 / (((r0 - db0) + ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoSPSD).sqrt()))
        + (ev3 / (((r0 + db0) - ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoSPSD).sqrt()))
        + (ev3 / (((r0 + db0) + ((1.0_f64).sqrt() * dsa0)).powi(2) + rhoSPSD).sqrt()))
        + (ev2 / (((r0 - db0).powi(2) + ((1.0_f64).sqrt() * dsa0).powi(2)) + rhoSPSD).sqrt()))
        - (ev2 / (((r0 + db0).powi(2) + ((1.0_f64).sqrt() * dsa0).powi(2)) + rhoSPSD).sqrt())));
    let DDQtzx_onehalfQtxy_SPUz = (-(((((((-ev3)
        / (((r0 - db0) - ((1.0_f64).sqrt() * dda0)).powi(2) + rhoSPDD).sqrt())
        - (ev3 / (((r0 - db0) + ((1.0_f64).sqrt() * dda0)).powi(2) + rhoSPDD).sqrt()))
        + (ev3 / (((r0 + db0) - ((1.0_f64).sqrt() * dda0)).powi(2) + rhoSPDD).sqrt()))
        + (ev3 / (((r0 + db0) + ((1.0_f64).sqrt() * dda0)).powi(2) + rhoSPDD).sqrt()))
        + (ev2 / (((r0 - db0).powi(2) + ((1.0_f64).sqrt() * dda0).powi(2)) + rhoSPDD).sqrt()))
        - (ev2 / (((r0 + db0).powi(2) + ((1.0_f64).sqrt() * dda0).powi(2)) + rhoSPDD).sqrt())));
    let qa0 = (qa0 / (2.0_f64).sqrt());
    let qb0 = (qb0 / (2.0_f64).sqrt());
    let qb0 = (qb0 * (2.0_f64).sqrt());
    let PPQtzx_onehalfQtxy_PPQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt())
        + (ev3 / (((r0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / (((r0 + qb0).powi(2) + (qa0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / (((r0 - qb0).powi(2) + (qa0).powi(2)) + rhoPPPP).sqrt()))
        + (ev4 / (((r0 - qb0) + qa0).powi(2) + rhoPPPP).sqrt()))
        + (ev4 / (((r0 + qb0) - qa0).powi(2) + rhoPPPP).sqrt()))
        + (ev4 / (((r0 + qb0) + qa0).powi(2) + rhoPPPP).sqrt()))
        + (ev4 / (((r0 - qb0) - qa0).powi(2) + rhoPPPP).sqrt()))
        - (ev3 / (((r0 - qa0).powi(2) + (qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / (((r0 + qa0).powi(2) + (qb0).powi(2)) + rhoPPPP).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt())
                + (ev2 / (((r0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
                - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (qb0).powi(2)) + rhoPPPP).sqrt()))));
    let DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt())
        + (ev3 / (((r0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / (((r0 + dsa0).powi(2) + (qb0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / (((r0 - dsa0).powi(2) + (qb0).powi(2)) + rhoPPSD).sqrt()))
        + (ev4 / (((r0 - dsa0) + qb0).powi(2) + rhoPPSD).sqrt()))
        + (ev4 / (((r0 + dsa0) - qb0).powi(2) + rhoPPSD).sqrt()))
        + (ev4 / (((r0 + dsa0) + qb0).powi(2) + rhoPPSD).sqrt()))
        + (ev4 / (((r0 - dsa0) - qb0).powi(2) + rhoPPSD).sqrt()))
        - (ev3 / (((r0 - qb0).powi(2) + (dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / (((r0 + qb0).powi(2) + (dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt())
                + (ev2 / (((r0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
                - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dsa0).powi(2)) + rhoPPSD).sqrt()))));
    let DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy = (((((((((((ev3
        / (((r0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt())
        + (ev3 / (((r0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / (((r0 + dda0).powi(2) + (qb0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / (((r0 - dda0).powi(2) + (qb0).powi(2)) + rhoPPDD).sqrt()))
        + (ev4 / (((r0 - dda0) + qb0).powi(2) + rhoPPDD).sqrt()))
        + (ev4 / (((r0 + dda0) - qb0).powi(2) + rhoPPDD).sqrt()))
        + (ev4 / (((r0 + dda0) + qb0).powi(2) + rhoPPDD).sqrt()))
        + (ev4 / (((r0 - dda0) - qb0).powi(2) + rhoPPDD).sqrt()))
        - (ev3 / (((r0 - qb0).powi(2) + (dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / (((r0 + qb0).powi(2) + (dda0).powi(2)) + rhoPPDD).sqrt()))
        - (0.25_f64
            * (((ev2 / (((r0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt())
                + (ev2 / (((r0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
                - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dda0).powi(2)) + rhoPPDD).sqrt()))));
    let qb0 = (qb0 / (2.0_f64).sqrt());
    let dsa0 = (dsa0 / (2.0_f64).sqrt());
    let dda0 = (dda0 / (2.0_f64).sqrt());
    let PPQpiz_PPQpiz = ((((((((ev3
        / ((((r0 + qa0) - qb0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt())
        - (ev3 / ((((r0 + qa0) - qb0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / ((((r0 + qa0) + qb0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt()))
        + (ev3 / ((((r0 + qa0) + qb0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / ((((r0 - qa0) - qb0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt()))
        + (ev3 / ((((r0 - qa0) - qb0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        + (ev3 / ((((r0 - qa0) + qb0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev3 / ((((r0 - qa0) + qb0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()));
    let DSQpiz_PPQpiz = ((((((((ev3
        / ((((r0 + qb0) - dsa0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt())
        - (ev3 / ((((r0 + qb0) - dsa0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / ((((r0 + qb0) + dsa0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt()))
        + (ev3 / ((((r0 + qb0) + dsa0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / ((((r0 - qb0) - dsa0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt()))
        + (ev3 / ((((r0 - qb0) - dsa0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        + (ev3 / ((((r0 - qb0) + dsa0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev3 / ((((r0 - qb0) + dsa0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()));
    let DDQpiz_PPQpiz = ((((((((ev3
        / ((((r0 + qb0) - dda0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt())
        - (ev3 / ((((r0 + qb0) - dda0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / ((((r0 + qb0) + dda0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt()))
        + (ev3 / ((((r0 + qb0) + dda0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / ((((r0 - qb0) - dda0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt()))
        + (ev3 / ((((r0 - qb0) - dda0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        + (ev3 / ((((r0 - qb0) + dda0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev3 / ((((r0 - qb0) + dda0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()));
    let dsa0 = (dsa0 * (2.0_f64).sqrt());
    let dda0 = (dda0 * (2.0_f64).sqrt());
    let qb0 = (qb0 * (2.0_f64).sqrt());
    let PPQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt())
        + (ev2 / (((r0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (qb0).powi(2)) + rhoPPPP).sqrt()));
    let DSQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt())
        + (ev2 / (((r0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dsa0).powi(2)) + rhoPPSD).sqrt()));
    let DDQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt())
        + (ev2 / (((r0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dda0).powi(2)) + rhoPPDD).sqrt()));
    let qb0 = (qb0 / (2.0_f64).sqrt());
    let qb0 = (qb0 * (2.0_f64).sqrt());
    let tildaPPQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qa0 - qb0).powi(2)) + rhoPPPP).sqrt())
        + (ev2 / (((r0).powi(2) + (qa0 + qb0).powi(2)) + rhoPPPP).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qa0).powi(2)) + (qb0).powi(2)) + rhoPPPP).sqrt()));
    let tildaDSQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qb0 - dsa0).powi(2)) + rhoPPSD).sqrt())
        + (ev2 / (((r0).powi(2) + (qb0 + dsa0).powi(2)) + rhoPPSD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dsa0).powi(2)) + rhoPPSD).sqrt()));
    let tildaDDQxy_PPQxy = (((ev2 / (((r0).powi(2) + (qb0 - dda0).powi(2)) + rhoPPDD).sqrt())
        + (ev2 / (((r0).powi(2) + (qb0 + dda0).powi(2)) + rhoPPDD).sqrt()))
        - (ev1 / ((((r0).powi(2) + (qb0).powi(2)) + (dda0).powi(2)) + rhoPPDD).sqrt()));
    let qb0 = (qb0 / (2.0_f64).sqrt());
    output[396] = ((tildaDSQxy_PPQxy * 1.0_f64) * 1.0_f64);
    output[308] = ((DPUpi_SPUpi * 1.0_f64) * 1.0_f64);
    output[353] = ((DPUpi_PPQpiz * 1.0_f64) * 1.0_f64);
    output[174] = ((DPUpi_SPUpi * 1.0_f64) * 1.0_f64);
    output[219] = ((DPUpi_PPQpiz * 1.0_f64) * 1.0_f64);
    output[44] =
        (((DDq_Sq * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64));
    output[269] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * (-0.666667_f64)));
    output[449] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * (-0.666667_f64)));
    output[89] = (((DDq_SPUz * 1.0_f64) * 1.0_f64)
        + ((DDQtzx_onehalfQtxy_SPUz * (-1.333333_f64)) * 1.0_f64));
    output[134] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * 1.333333_f64));
    output[150] = ((DSQpiz_SPUpi * 1.0_f64) * 1.0_f64);
    output[195] = ((DSQpiz_PPQpiz * 1.0_f64) * 1.0_f64);
    output[17] = ((DPUz_Sq * 1.0_f64) * 1.0_f64);
    output[242] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)));
    output[422] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)));
    output[62] = ((DPUz_SPUz * 1.0_f64) * 1.0_f64);
    output[107] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64));
    output[151] = ((DPUpi_SPUpi * 1.0_f64) * 1.0_f64);
    output[196] = ((DPUpi_PPQpiz * 1.0_f64) * 1.0_f64);
    output[311] = ((DDQpiz_SPUpi * 1.0_f64) * 1.0_f64);
    output[356] = ((DDQpiz_PPQpiz * 1.0_f64) * 1.0_f64);
    output[20] =
        (((DDq_Sq * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64));
    output[245] = ((((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * (-0.666667_f64)))
        + ((DDQxy_PPQxy * 1.0_f64) * 1.0_f64));
    output[425] = ((((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * (-0.666667_f64)))
        - ((DDQxy_PPQxy * 1.0_f64) * 1.0_f64));
    output[65] =
        (((DDq_SPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_SPUz * 0.666667_f64) * 1.0_f64));
    output[110] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * 1.333333_f64));
    output[10] = ((DSQtzx_onehalfQtxy_Sq * 1.154701_f64) * 1.0_f64);
    output[235] = (((DSQtzx_onehalfQtxy_Sq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.154701_f64) * (-0.666667_f64)));
    output[415] = (((DSQtzx_onehalfQtxy_Sq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.154701_f64) * (-0.666667_f64)));
    output[55] = ((DSQtzx_onehalfQtxy_SPUz * 1.154701_f64) * 1.0_f64);
    output[100] = (((DSQtzx_onehalfQtxy_Sq * 1.154701_f64) * 1.0_f64)
        + ((DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.154701_f64) * 1.333333_f64));
    output[147] = ((DPUpi_SPUpi * (-0.57735_f64)) * 1.0_f64);
    output[192] = ((DPUpi_PPQpiz * (-0.57735_f64)) * 1.0_f64);
    output[283] = (((DPUpi_SPUpi * 1.0_f64) * 1.0_f64) * (-0.57735_f64));
    output[328] = ((((-DPUpi_PPQpiz) * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[11] = ((DPUz_Sq * 1.154701_f64) * 1.0_f64);
    output[236] = (((DPUz_Sq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_PPQtzx_onehalfQtxy * 1.154701_f64) * (-0.666667_f64)));
    output[416] = (((DPUz_Sq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_PPQtzx_onehalfQtxy * 1.154701_f64) * (-0.666667_f64)));
    output[56] = ((DPUz_SPUz * 1.154701_f64) * 1.0_f64);
    output[101] = (((DPUz_Sq * 1.154701_f64) * 1.0_f64)
        + ((DPUz_PPQtzx_onehalfQtxy * 1.154701_f64) * 1.333333_f64));
    output[400] = (((tildaDDQxy_PPQxy * 1.0_f64) * 1.0_f64) * 1.1547005383793_f64);
    output[154] = ((DDQpiz_SPUpi * 0.57735_f64) * 1.0_f64);
    output[199] = ((DDQpiz_PPQpiz * 0.57735_f64) * 1.0_f64);
    output[14] =
        (((DDq_Sq * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_Sq * 1.333333_f64) * 1.0_f64));
    output[239] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.333333_f64) * (-0.666667_f64)));
    output[419] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.333333_f64) * (-0.666667_f64)));
    output[59] =
        (((DDq_SPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_SPUz * 1.333333_f64) * 1.0_f64));
    output[104] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_Sq * 1.333333_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 1.333333_f64) * 1.333333_f64));
    output[291] = ((DSQpiz_SPUpi * 1.0_f64) * 1.0_f64);
    output[336] = ((DSQpiz_PPQpiz * 1.0_f64) * 1.0_f64);
    output[24] = ((DPUz_Sq * 1.0_f64) * 1.0_f64);
    output[249] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)));
    output[429] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)));
    output[69] = ((DPUz_SPUz * 1.0_f64) * 1.0_f64);
    output[114] =
        (((DPUz_Sq * 1.0_f64) * 1.0_f64) + ((DPUz_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64));
    output[292] = ((DPUpi_SPUpi * 1.0_f64) * 1.0_f64);
    output[337] = ((DPUpi_PPQpiz * 1.0_f64) * 1.0_f64);
    output[177] = ((DDQpiz_SPUpi * 1.0_f64) * 1.0_f64);
    output[222] = ((DDQpiz_PPQpiz * 1.0_f64) * 1.0_f64);
    output[386] = ((tildaDDQxy_PPQxy * 1.0_f64) * 1.0_f64);
    output[295] = (((DDQpiz_SPUpi * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[340] = (((DDQpiz_PPQpiz * 1.0_f64) * 1.0_f64) * 0.57735026918963_f64);
    output[27] =
        (((DDq_Sq * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64));
    output[252] = ((((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * (-0.666667_f64)))
        - ((DDQxy_PPQxy * 1.0_f64) * 1.0_f64));
    output[432] = ((((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * (-0.666667_f64)))
        + ((DDQxy_PPQxy * 1.0_f64) * 1.0_f64));
    output[72] =
        (((DDq_SPUz * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_SPUz * 0.666667_f64) * 1.0_f64));
    output[117] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_Sq * 0.666667_f64) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * 0.666667_f64) * 1.333333_f64));
    output[253] = ((DSQxy_PPQxy * 1.0_f64) * 1.0_f64);
    output[433] = (((-DSQxy_PPQxy) * 1.0_f64) * 1.0_f64);
    output[165] = ((DPUpi_SPUpi * 1.0_f64) * 1.0_f64);
    output[210] = ((DPUpi_PPQpiz * 1.0_f64) * 1.0_f64);
    output[301] = (((-DPUpi_SPUpi) * 1.0_f64) * 1.0_f64);
    output[346] = (((-DPUpi_PPQpiz) * 1.0_f64) * 1.0_f64);
    output[168] = ((DDQpiz_SPUpi * 1.0_f64) * 1.0_f64);
    output[213] = ((DDQpiz_PPQpiz * 1.0_f64) * 1.0_f64);
    output[257] = ((DDQxy_PPQxy * 1.154701_f64) * 1.0_f64);
    output[437] = (((-DDQxy_PPQxy) * 1.154701_f64) * 1.0_f64);
    output[304] = (((-DDQpiz_SPUpi) * 1.0_f64) * 1.0_f64);
    output[349] = (((-DDQpiz_PPQpiz) * 1.0_f64) * 1.0_f64);
    output[35] =
        (((DDq_Sq * 1.0_f64) * 1.0_f64) + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64));
    output[260] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * (-0.666667_f64)));
    output[440] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * (-0.666667_f64)))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * (-0.666667_f64)));
    output[80] = (((DDq_SPUz * 1.0_f64) * 1.0_f64)
        + ((DDQtzx_onehalfQtxy_SPUz * (-1.333333_f64)) * 1.0_f64));
    output[125] = (((((DDq_Sq * 1.0_f64) * 1.0_f64)
        + ((DDq_PPQtzx_onehalfQtxy * 1.0_f64) * 1.333333_f64))
        + ((DDQtzx_onehalfQtxy_Sq * (-1.333333_f64)) * 1.0_f64))
        + ((DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy * (-1.333333_f64)) * 1.333333_f64));
    output
}
